### ISSUE TITLE
JS code must be linted

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#10]
We should add a way to lint the aqua JS code.

**Comment by samreid** [comment]
For instance, `cd aqua; grunt lint` should report lint errors for aqua.

**Comment by samreid** [comment]
I'm not planning to work on aqua for a while, unassigning.

**Comment by samreid** [comment]
@jonathanolson does bayes lint-everything hit aqua JS code?

**Comment by jonathanolson** [comment]
It lints the version of aqua code that is being run (which is not always the latest master, since aqua won't pull itself). Is that sufficient?

**Comment by samreid** [comment]
That seems sufficient for now since that file isn't changing too much, and when it does change we probably pull it on bayes.
