### ISSUE TITLE
qunitLaunchAfterHooks is not a function

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#102]
@jonathanolson reported:

> Is this still randomly occurring and failing out commits, or is this a sign of something wrong?:
ok: false,
 message: 'caught exception Error: Evaluation failed: TypeError: window.qunitLaunchAfterHooks is not a function\n' +
  '  at __puppeteer_evaluation_script__:12:16'
}

> Was also a case of "I re-ran the failed commits, and it worked the second time", and each case of "I have to commit to every repo" has resulted in ~3 randomly failing commit hooks

I said I would try to investigate this on Monday.

**Comment by samreid** [comment]
I haven't been able to reproduce this problem by running `node ../perennial/js/scripts/hook-pre-commit.js` many times in axon.  The process for assigning `window.qunitLaunchAfterHooks` looks brittle though, perhaps there is a better way to do it.

**Comment by samreid** [comment]
I added a polling loop which runs if the function is not ready during startup.  @jonathanolson can you please run a test like this?

* Before pulling, run `node ../perennial/js/scripts/hook-pre-commit.js` several times in axon, and record how many times it has the failure
* Pull changes and run that again to see if the problem is corrected.

**Comment by zepumph** [comment]
I don't think we have experienced this error in quite some time. I'm going to close this issue, but feel free to reopen if there is more to discuss.
