### ISSUE TITLE
CT should test assertSlow with `?eall`

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#107]
I was curious to see that `assertSlow` via `?eall` was failing on multi screen sims over in https://github.com/phetsims/joist/issues/656. At dev meeting it was decided that we will do some limited testing of CT. For timing, we will just take a random sim and run this on that sim.

I will also update QA about how this type of test may exist, and to look at how often the test is run, not just the whole sim row, to see if it is still a problem.

**Comment by zepumph** [comment]
@jonathanolson, I want this to be a really low priority test that only happens if CT is bored, can you please review the above commit? Any thoughts?

**Comment by jonathanolson** [comment]
I'm fine with this being tested, but I recall a lot of cases where `?eall` will break that I haven't investigated yet (a number of different failure modes with random scenery operations that should be valid), so it's likely to show a lot of errors.

**Comment by zepumph** [comment]
I see. I didn't realize that `eall` wasn't supposed to pass fuzzing. I have added assertions to `eall` when I felt like they were too slow for running with `ea`. Perhaps I should reevaluate that pattern if we find that `eall` holds too many "acceptable errors" during CT testing.

**Comment by zepumph** [comment]
CT is looking pretty clear! I think we should close this issue. We can reevaluate if we find cases where eall is failing and we don't want to fix it.
