### ISSUE TITLE
Memory testing using `window.performance.memory`?

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#108]
@pixelzoom found many performance related issues recently during natural selection memory testing. I was curious about the potential of using `performance.memory` to make automated tests that find memory leaks. At the very least a naive and simple implementation could be easy to make, and catch the largest/most-important problems.

This is a non-standard api (only for chrome), see https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory. Still we could use this for some good, and likely add it to CT to be run conditionally only on chrome. This feels like the sort of thing @samreid may be interested in thinking about, so I will co-assign, but no expectations here, this is just an idea.

**Comment by samreid** [comment]
I believe this is already in place using main/joist/js/MemoryMonitor.js and running on CT for some fuzzes.

**Comment by zepumph** [comment]
I feel like there could be some interesting work done in this issue, but nothing seems easy or a reasonable amount of work to spend right now. 

Some ides:
CT to compare memory of current sim to a previous snapshot (published sim?)
A way to specify an "ideal" memory for a sim, and then test against that. 

I think for now we should close this issue.
