### ISSUE TITLE
add phetmarks support for running colors.html

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#110]
If you add `"colorProfile": true`, to package.json and run `grunt update`, it creates `{{REPO}-colors.html`.  This file allows developers and designers to experiment with the color profile for a sim.   Running this colors.html file is not currently supported by phetmarks, which is inconvenient - you have to manually navigate to colors.html in a browser.

This has become more important because, (1) 25 sims currently have a colors.html file, and (2) over in https://github.com/phetsims/scenery-phet/issues/642, the proposal is to use ColorProfle in all news sims. As @arouinfar said in https://github.com/phetsims/scenery-phet/issues/642#issuecomment-726920361: 

> Having a ColorProfile also makes it **much** simpler for designers to play with colors on a local copy.

Assigning to @ariel-phet to prioritize and assign.

**Comment by jonathanolson** [comment]
![image](https://user-images.githubusercontent.com/480878/99692162-3975d400-2a47-11eb-85c3-06b67b70470b.png)

This exists already I believe, currently under "Color Editor" as seen above.

**Comment by pixelzoom** [comment]
I guess this means "it's already supported, you just missed it".
