### ISSUE TITLE
Snapshot comparison to support non screenshot comparison methods

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#125]
Over in https://github.com/phetsims/perennial/issues/138, I want to compare PDOM description between two versions, and I feel like snapshot comparison could easily be build up to do that. First it will require a couple of minor changes to how the messages are formatted, and some terminology changes so that it isn't so based on "screenshots". Basically I'm thinking that a "snapshot" is just one load of the sim, in which N fuzzing steps occur, and data is taken in between each one. That data to me is a "frame," in which a screenshot is captured, but potentially other data too. Then an entire "snapshot" is also hashed all together. I'm going to commit what's in my working copy for review and discussion.

Also noting that other improvements may come out of https://github.com/phetsims/aqua/issues/122 along the way.

Tagging @jonathanolson to note that I'm working in snapshot comparison at this time.

**Comment by zepumph** [comment]
This is enough of a start to get going on https://github.com/phetsims/aqua/issues/127. @jonathanolson does this commit seems reasonable to you?

**Comment by jonathanolson** [comment]
Sounds perfectly reasonable!
