### ISSUE TITLE
Improve CT coverage when fuzzing ComboBox, Dialog, and similar UI components.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#136]
For some UI components, it's difficult to get adequate code coverage with fuzz testing. For example...

Geometric Optics has 3 different scenes that are selected via a ComboBox. But selecting from a ComboBox involves 2 actions: pressing the button to pop up the list, then making a selection from the list.  Because of how fuzzing works, the default setting for the ComboBox (the default scene) is receiving most of the testing.  I haven’t quantified, but manually watching a fuzz for a couple of minutes, I would guess that the default scene is receiving 90% (or more) of the testing.  And part of the other 2 scenes are likely never being fuzzed, and are receiving no coverage.  This is not good, because the scene have very different code paths that need to be exercised.   

Dialogs have a similar problem.  For example, there was a bug in GO’s Options dialog that had been there for > 2 months before CT finally hit it.  Opening the Options dialog is not likely to happen with fuzz testing because it involves 2 actions: popping up the PhET menu, then making a selection. And when a Dialog is opened, it's likely to be immediately closed by clicking outside the dialog.  Fuzz testing all of the UI components in the Options dialog is therefore unlikely. 

So this seems to be a general problem with any UI component that requires multiple interactions to make a selection.  Is there something that can be done to address this?

As a workaround for Geometric Optics…. I could (and may) create a private query parameter that sets the initial ComboBox selection, then add sim-specific CT fuzz tests for the 2 non-default scenes.  That will put more of a load on CT, which is already overloaded.  It doesn't address the Options dialog. And it doesn't address the problem for other sims.

Labeled for discussion at dev meeting.  Also assigning to @jonathanolson - as the primary author of CT, I'd like to hear his thoughts.

**Comment by pixelzoom** [comment]
> I haven’t quantified, but manually watching a fuzz for a couple of minutes, I would guess that the default scene is receiving 90% (or more) of the testing.

I have now quantified, see https://github.com/phetsims/geometric-optics/issues/397#issuecomment-1075337164.  The default scene in Geometric Optics is receiving ~96% of the fuzz time.  Since the scenes in Geometric Optics are very different, this means that ~2/3 of this sim is not being adequated exercised by fuzz testing.

**Comment by pixelzoom** [comment]
Scene-specific fuzz tests have been added to listContinuousTest.js for geometric-optics, see above commits.

**Comment by samreid** [comment]
I wrote up an alternative strategy for exercising CT coverage by fuzzing the Property values directly in https://github.com/phetsims/axon/issues/383, @pixelzoom can you please review and comment?

**Comment by jonathanolson** [comment]
Also this is an idea I haven't brought up for a while, but my vision was NOT originally to have fuzzing be the primary testing strategy. Recording input of a user running through an entire sim's interface seemed like the most likely primary method of testing its functionality.

**Comment by pixelzoom** [comment]
> ... @pixelzoom can you please review and comment?

Done, see https://github.com/phetsims/axon/issues/383#issuecomment-1085100042

**Comment by chrisklus** [comment]
Some possible improvements:

SR: Option for popups when fuzzing -  reduce the chance that the popup will be dismissed when clicking outside the popup to ensure that options/content in the popup is interacted with.

@pixelzoom is going to investigate to see if there's an easy way to do this for Popupable, ComboBoxListBox, and PhetMenu - see also BarrierRectangle.

**Comment by samreid** [comment]
This patch seemed to show a lot more dialogs and dialog options:

<details>

```diff

Index: js/BarrierRectangle.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/BarrierRectangle.js b/js/BarrierRectangle.js
--- a/js/BarrierRectangle.js	(revision fd385546623dda43a9970db84f0fc0d635b5b89f)
+++ b/js/BarrierRectangle.js	(date 1655401236589)
@@ -44,7 +44,9 @@
       phetioReadOnly: options.phetioReadOnly,
       fire() {
         assert && assert( modalNodeStack.length > 0, 'There must be a Node in the stack to hide.' );
-        modalNodeStack.get( modalNodeStack.length - 1 ).hide();
+        if ( Math.random() < 0.000001 ) {
+          modalNodeStack.get( modalNodeStack.length - 1 ).hide();
+        }
       }
     } ) );
 

```

</details>

**Comment by pixelzoom** [comment]
Slack:

@pixelzoom 
For https://github.com/phetsims/aqua/issues/136, we discussed reducing the probability that popups will be dismissed while fuzz testing.  For the purposes of CT, how should we define “while fuzz testing”?   There are 4 different fuzz-related query parameters: fuzz, fuzzBoard (sic), fuzzMouse, fuzzTouch.  Is testing for phet.chipper.queryParameter.fuzz sufficient? Or will that not increase popup coverage for accessibility fuzzing? (edited) 

@jessegreenberg 
Right, is `window.phet.chipper.isFuzzEnabled()` what you are looking for? In initialize-globals 

@pixelzoom 
Perfect, thanks. I had no idea that existed.

**Comment by pixelzoom** [comment]
Note that the approach that @samreid prototyped in https://github.com/phetsims/aqua/issues/136#issuecomment-1157957240 is what ComboBox currently does, see below.  It was added by me for https://github.com/phetsims/sun/issues/677, and refined by others.

```js
this.clickToDismissListener = {
      down: event => {

        // If fuzzing is enabled, exercise this listener some percentage of the time, so that this listener is tested.
        // The rest of the time, ignore this listener, so that the listbox remains popped up, and we test making
        // choices from the listbox. See https://github.com/phetsims/sun/issues/677
        // @ts-ignore chipper
        if ( !phet.chipper.isFuzzEnabled() || dotRandom.nextDouble() < 0.005 ) {

          // Ignore if we click over the button, since the button will handle hiding the list.
          if ( !( event.trail.containsNode( this.button ) || event.trail.containsNode( this.listBox ) ) ) {
            this.hideListBox();
          }
        }
      }
    };
```

**Comment by pixelzoom** [comment]
Summary of the above commits:

* Used the same approach (as shown above) for BarrierRectangle (dialogs, PhET menu) and ComboBox (listbox).
* Made listbox stay open more often when fuzzing, by reducing its probability of closing from 0.25 to 0.005.
* Made dialogs and PhET menu stay open more often when fuzzing, with probability of closing 0.005.

To choose the value 0.005, I ran geometric-optics with `?fuzz` and observed it manually.  For smaller values, it seemed like dialogs (especially the keyboard help dialog) were open much too long, reducing coverage on other parts of the sim.  For large values, the coverage didn't look very good.  With 0.005,  I saw controls in the Options dialog being exercised.  And I saw the combo box in the upper-left of the screen being exercised (something that rarely happened with probability 0.25.)

@samreid could you please review?
