### ISSUE TITLE
CT: Unable to find local grunt

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#137]
In CT, aqua is on it’s 3rd cycle of not being able to find grunt.   This started at 1:06PM on 4/5/2022.

```
aqua : lint
Lint failed with status code 99:
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
Snapshot from 4/5/2022, 2:20:50 PM
```

**Comment by samreid** [comment]
I ran `npm install` in bayes `/data/share/phet/continuous-testing/aqua`.  Let's see if that's fixed in the next column.

**Comment by zepumph** [comment]
I don't see this issue anymore, and also I recently restarted CT and it said that it was missing an npm module, requiring me to npm install. aqua tasks all run on grunt now, so hopefully people have to npm install in aqua before anything is run. Closing
