### ISSUE TITLE
Red test with no explanation

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#14]
@jonathanolson I tried running aqua load-only test and saw red with no explanation.  Is this normal?

![image](https://cloud.githubusercontent.com/assets/679486/21083383/71511632-bfac-11e6-9137-fee704ef6282.png)

**Comment by samreid** [comment]
The explanation for Build A Molecule appeared much later, but there are other red sims with no explanation now:

![image](https://cloud.githubusercontent.com/assets/679486/21085223/4a98c042-bfcc-11e6-8a69-91a988941095.png)

**Comment by jonathanolson** [comment]
I think I've seen it once before, I'll look into it.

**Comment by samreid** [comment]
It looks like this may be caused by a slow sim load. For instance with testTime=10000, if build a molecule takes 15sec to load, then it could show red with no error text.

**Comment by samreid** [comment]
Ideally, the testTime should be the time after the sim finishes launching.  Perhaps @jonathanolson can consider this when making aqua upgrades in the future.

**Comment by pixelzoom** [comment]
@samreid can this issue be closed?

**Comment by pixelzoom** [comment]
@samreid can this issue be closed? It seems somewhat ancient and irrelevant now.

**Comment by samreid** [comment]
I've also seen red with no explanation when tabbing away then tabbing back, but knowing about this limitation, I haven't had any other problems with this.  Closing.
