### ISSUE TITLE
"Connection closed" error on CT

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/aqua#140]
CT often reports an error like this:

> Error: Protocol error: Connection closed. Most likely the page has been closed.

I has popped up from time to time but is much more visible now that CT is sending notifications to slack. Why is this happening and how should we investigate?

Adding to dev meeting agend to decide who should investigate.

**Comment by jonathanolson** [comment]
QuickServer noted this in its error lods too:
```
Caught interrupt signal, exiting
Fatal error: Puppeteer was unable to kill the process which ran the browser binary.
This means that, on future Puppeteer launches, Puppeteer might not be able to launch the browser.
Please check your open processes and ensure that the browser processes that Puppeteer launched have been killed.
If you think this is a bug, please report it on the Puppeteer issue tracker.
Error cause: Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:200:13)
    at BrowserRunner.kill (/data/share/phet/continuous-quick-server/perennial/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:189:29)
    at process.emit (events.js:327:22)
    at process.exit (internal/process/per_thread.js:169:15)
    at process.<anonymous> (/data/share/phet/continuous-quick-server/chipper/js/grunt/Gruntfile.js:27:11)
    at process.emit (events.js:327:22)
```

**Comment by zepumph** [comment]
I will take the lead on this issue. I think it is closely related to https://github.com/phetsims/aqua/issues/143 and discussion I was having with @jonathanolson about killing all chrome instances on bayes every 15 minutes.

**Comment by zepumph** [comment]
Since creating https://github.com/phetsims/aqua/issues/143, we have not had any occurrences of this. We removed the `killall chrome` cron job, which was in all likelihood causing this. I'm going to close this issue.
