### ISSUE TITLE
Create a CT client based on Puppeteer.

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#143]
This way, we wouldn't need to have to kill all chrome. Related to https://github.com/phetsims/perennial/issues/268. 

@jonathanolson and I also noticed that we could potentially use selenium, and or a headless firefox implementation with the same interface for CT's client side module.

**Comment by zepumph** [comment]
I see that I, for fun, made a local Puppeteer client that is already doing a lot of what we want here:

https://github.com/phetsims/aqua/blob/042160003a1372489991e1e347bbebfe3322a1c9/js/local/puppeteerHelpCT.js

I'll start with that.

**Comment by zepumph** [comment]
Good progress today! I made ContinuousServerClient which uses Workers to kick off instances of Puppeteer. I was able to test this locally and saw my results showing up on CT's report at https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-report.html?maxColumns=5. From here I would like @jonathanolson to review.

My main questions are about all of the options passed to chrome in the current headless testing:

`google-chrome --headless --disable-gpu --disable-software-rasterizer --remote-debugging-port=94${1} --enable-precise-memory-info --enable-logging=stderr --v=1 "https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-loop.html?id=Bayes%20Chrome"`

Are there any of these that we should transfer in to Puppeteer for our purposes? It would be easy to pass them in via puppeteer.launch(); (https://github.com/puppeteer/puppeteer/blob/v14.1.1/docs/api.md#puppeteerlaunchoptions).


Even before the review is complete, I'm going to start it up on CT with less clients, and delete just a couple of the chrome screens. This way we can start to get some on-server testing to see if this works.

If all goes well with the review, next steps are to convert all headless chromes to this process, and to remove the killall chrome cronjob. This will most likely fix https://github.com/phetsims/aqua/issues/140.

**Comment by zepumph** [comment]
- [ ] Another question: Should we have each puppeteer load last longer than 15 minutes?

**Comment by zepumph** [comment]
- [ ] If we get the go-ahead, I will want to update documentation about this procress instead of using the loop shell script.

**Comment by zepumph** [comment]
I was looking through CT results and felt confident enough to transfer all testing onto this client. I also felt like there is potential that this switch may help solve the issues we are having over in https://github.com/phetsims/special-ops/issues/228. @jonathanolson please continue with the review knowing that this client is our entire testing client for CT at this time (16 instances of puppeteer.

**Comment by zepumph** [comment]
Something I'm noticing in the logs is that there are a fair number of "info: puppeteer error: Error: Page crashed!" We now have logs to see that this is happening (~15 times in 15 minutes). I see two possible reasons:

1. Puppeteer doesn't like having 16 instances running in parallel (I don't think this is the problem)
2. This demonstrates that there is a CT test that is breaking the testing harness and may or may not be reporting back before the page fails and has to restart. In this case, we should learn a bit more with perhaps a bit more error logging.

**Comment by jonathanolson** [comment]
Any idea which page is crashing?

**Comment by zepumph** [comment]
Note I stopped this because of https://github.com/phetsims/aqua/issues/145.

**Comment by zepumph** [comment]
All has been good on the server. Over the weekend it looks like there were no issues with the client. We are just ready for a review now.

**Comment by jonathanolson** [comment]
I'm not sure I agree with https://github.com/phetsims/perennial/commit/34bcd56be90e157554623bfc78bb24dcd1ed7b8a. Usually things called `error` are a subtype of `Error`. Is that the case? (We could just resolve/reject with the error instead of wrapping it).

**Comment by jonathanolson** [comment]
Looks good, although I don't know how `parentPort.postMessage( error );` in the client would activate code in the server to note the error. How would that work? Is that just activating the "message"?

**Comment by jonathanolson** [comment]
Looks like this review was handled with commits above. Closing.
