### ISSUE TITLE
CT has a number of grey cells and tests seem slow/not being done

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/aqua#148]
From Slack:
>[Kathryn Woessner]
  [1 hour ago]
CT looks like not many tests are being done (lots of grey cells). Is this an issue?
[Sam Reid]
  [1 hour ago]
Maybe the lint failure is preventing builds?
[Kathryn Woessner]
  [1 hour ago]
Should I make an issue somewhere?
[Sam Reid]
  [1 hour ago]
Yes please.  Perhaps in the aqua repo?

**Comment by samreid** [comment]
I'll try pulling aqua on CT.

UPDATE: CT commands are running very slowly, including logging in, authenticating, etc.  I've been waiting 60+ seconds for `pm2 stop continuous-server` to complete.
UPDATE: I abandoned that command.

**Comment by zepumph** [comment]
I think this is likely related to @pixelzoom's post on slack, but things got worse over time. I made https://github.com/phetsims/aqua/issues/150 to track it.

**Comment by marlitas** [comment]
@zepumph... this seems like we might be able to close? I can at least removed the automated-testing label.
