### ISSUE TITLE
Add dedicated CT server

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/aqua#151]

**Comment by zepumph** [comment]
The goal for this is to have something ordered by July.

It isn't clear to me what the specs are on this. Let's discuss this further!

**Comment by mattpen** [comment]
[phet-server-july_21.pdf](https://github.com/phetsims/aqua/files/9726947/phet-server-july_21.pdf)

Here is the quote for the recent phet-server2 replacement. Do we want to go with something like this? 

Here is the machine on dell.com, where we can see pricing for various memory/cpu/storage options: https://www.dell.com/en-us/shop/cty/pdp/spd/poweredge-r440/pe_r440_tm_vi_vp_sb. The pricing will be slightly different as we'll purchase it through CU Marketplace, which I believe has some discounts but I'm not aware of the details on that.  Maybe @oliver-phet could help.

Should we schedule a meeting to discuss internally? Or should I reach out to Jason to schedule a meeting with him to discuss (with MK and optionally JO)?

**Comment by zepumph** [comment]
I'm curious about what memory is right. 8GB felt a bit low, but I'm not really sure:

![image](https://user-images.githubusercontent.com/6856943/194377778-11ba5f30-0b61-42ab-94dd-c88e0d5003f4.png)


Or is that 8GB per core? 

I also didn't really understand the "best practices" notes and if  we were doing things correctly.

**Comment by mattpen** [comment]
That's 8GB per memory stick in the screen shot, you can hit the + and add more sticks.  On phet-server2 we have 8x8GB configured.

**Comment by mattpen** [comment]
@jonathanolson @zepumph - do we know what our limiting factors are for CT? What resources should we prioritize increasing?

According to https://bayes.colorado.edu/xymon/ (creds are in the doc), it almost always reports that bayes.colorado.edu is maxed out on CPU.  However, that report isn't always measuring things correctly, so we should use it as a guide to investigate and not final answers.

**Comment by kathy-phet** [comment]
Thanks, Matt. For getting this issue rolling. Maybe one 30 minute meeting internally with you, JO, MK. And then a meeting with Jason. 

Also @oliver-phet - Do we have the original bayes machine quote from CU OIT? Can you attach it here.

**Comment by oliver-phet** [comment]
> Also @oliver-phet - Do we have the original bayes machine quote from CU OIT? Can you attach it here.

Is this what you were asking for? The 2015 machine specs?
[Dell912687874.pdf](https://github.com/phetsims/aqua/files/9747270/Dell912687874.pdf)

**Comment by zepumph** [comment]
We have set up a meeting for this afternoon and will report back.

**Comment by mattpen** [comment]
Configuration that we agreed upon in a meeting with @jonathanolson @oliver-phet @kathy-phet @zepumph and @mattpen 

https://www.dell.com/en-us/shop/cty/pdp/spd/poweredge-r440/pe_r440_tm_vi_vp_sb?configurationid=d8f3f518-daf6-460b-b82e-bac10d0b9dbc

**Comment by zepumph** [comment]
@oliver-phet pointed out that the "max" memory slots per CPU for this processor is 6:

https://ark.intel.com/content/www/us/en/ark/products/192437/intel-xeon-gold-6230-processor-27-5m-cache-2-10-ghz.html

**Comment by mattpen** [comment]
I sent an email to Jason requesting a meeting time.

**Comment by oliver-phet** [comment]
(Maybe there isn't anything we can do about this) but the processor we have selected is a "2nd Gen" and Intel launched their "3rd Gen" Xeon Scalable processors in Q2'21.
https://www.intel.com/content/www/us/en/products/details/processors/xeon/scalable/gold/products.html

**Comment by mattpen** [comment]
We'd probably have to select a different motherboard or housing I would imagine. I think Jason could help us with this if we're interested in using 3rd gen instead of 2nd.

**Comment by zepumph** [comment]
Looks like the 6230 (what we were looking at with 40T per core) was released Q2'19

**Comment by kathy-phet** [comment]
A different PowerEdge has those newer options: 
https://www.dell.com/en-us/shop/servers-storage-and-networking/poweredge-r550-rack-server/spd/poweredge-r550/pe_r550_tm_vi_vp_sb

**Comment by kathy-phet** [comment]
This one has Platinum processor options with crazy number of threads 
https://www.dell.com/en-us/shop/servers-storage-and-networking/poweredge-r650-rack-server/spd/poweredge-r650/pe_r650_14796_vi_vp

**Comment by zepumph** [comment]
I got pretty far on this one, but realized they don't have an option for HDDs (only SSD), so that added ~5000 to the final price:

https://www.dell.com/en-us/shop/servers-storage-and-networking/poweredge-r650-rack-server/spd/poweredge-r650/pe_r650_tm_vi_vp_sb?view=configurations&configurationid=6da9fe31-eaf5-4551-8a80-1574b75d0e07

**Comment by kathy-phet** [comment]
650 is showing SAS HD options for me?

**Comment by kathy-phet** [comment]
Bonus of r650 is its in stock instead of out of stock. https://www.dell.com/en-us/shop/servers-storage-and-networking/poweredge-r650-rack-server/spd/poweredge-r650/pe_r650_14796_vi_vp?configurationid=fd2911a3-0ef7-4116-ae2b-1f08c6b9bb1b
With platenium 64T cores ... but maybe not everything we need.

**Comment by oliver-phet** [comment]
Clicking around a bit more... I think the R440 chassis was limiting our CPU choices. This R450 dual CPU rack allows 3rd gen processors:
https://www.dell.com/en-us/shop/servers-storage-and-networking/poweredge-r450-rack-server/spd/poweredge-r450/pe_r450_15127_vi_vp?view=configurations&configurationid=782abc84-b21c-4b11-baf8-39b7219aa6c2

**Comment by zepumph** [comment]
Questions I have for our next meeting:

1. Ideal memory per CPU
2. If one CPU with X threads is better or worse than 2 CPUs each with X/2 threads.
3. If there is a specific space requirement on the "rack" we are going to mount to

**Comment by samreid** [comment]
I recently had a good experience using GitHub Codespaces while investigating https://github.com/phetsims/chipper/issues/1353 and it seemed like it might also work for CT since you can clone many repos, install things and run programs, including web servers. Running an unbuilt sim over port forwarding didn't work, but it's unclear whether that would affect CT self-loading (no port forwarding). Of course it would be possible to run into other incompatibility problems. We previously (a few years ago) determined that cloud hosting would be too expensive (AWS, I believe), but now that Codespaces came out I wanted to double check that quote.

The pricing is listed at https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces, which shows that 1 hour on a 32 core machine is $2.88.  A month has 730 hours, so that works out to $2100/month, which sounds pretty expensive.  To match the phet-server-2 quote above, the break-even point would be at $12,125.34/$2100, which is only 5.7 months. I don't think we would want to do something like this without a breakeven point at 4+ years. But to get to that price, we would have to sacrifice cores or not run it 24/7.  Storage is quoted at $0.07 per 1GB/month, and I did not count it in the calculation.  Likewise I did not check AWS to see how their prices compare today.

Anyways, just wanted to jot down a paper trail in case someone (like future me) asks about cloud computing.

**Comment by mattpen** [comment]
> ---------- Forwarded message ---------
> From: Jason Edward Hill <jason@colorado.edu>
> Date: Tue, Nov 8, 2022 at 1:51 PM
> Subject: Re: Purchase advice on a new PhET server for a testing machine (re BAYES recent failure)
> To: Kathy Perkins <katherine.perkins@colorado.edu>, Matthew Pennington <Matthew.Pennington@colorado.edu>
> Cc: Jonathan B Olson <jonathan.olson@colorado.edu>, Michael J Kauzmann <Michael.Kauzmann@colorado.edu>, Oliver Pascal Nix <Oliver.Nix@colorado.edu>
> 
> 
> Hi all,
> 
> Again, my apologies for the delay on this.  I've attached a quote.  It includes all of what you specified, and I added the 2-port SFP28 NIC, got rid of the power cords, added a ready-rails mount without cable management.
> 
> Please look it over and let me know what you think.
> 
> Cheers,
> Jason

[Phet-Dev.pdf](https://github.com/phetsims/aqua/files/10016197/Phet-Dev.pdf)

@kathy-phet would like us all to review Jason's comments in his latest email and the quote he provided (included above), and either comment with changes that should be made or approve the purchase

- @mattpen 
    - [ ] I approve the quote as is
    - [ ] Changes are needed (add a comment below)
- @jonathanolson 
    - [ ] I approve the quote as is
    - [ ] Changes are needed (add a comment below)
- @zepumph 
    - [ ] I approve the quote as is
    - [ ] Changes are needed  (add a comment below)
- @oliver-phet 
    - [ ] I approve the quote as is
    - [ ] Changes are needed  (add a comment below)
- @kathy-phet 
    - [ ] I approve the quote as is
    - [ ] Changes are needed (add a comment below)

**Comment by oliver-phet** [comment]
I went through the quote process and generated an identical server with the same price, looks good to me.

**Comment by kathy-phet** [comment]
I sent Jason an email asking if we should run this by the Dell Rep.
