### ISSUE TITLE
Local aqua doesn't respect sourcemaps

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#153]
Like issue https://github.com/phetsims/chipper/issues/1140 but for local aqua.

@pixelzoom said:

> The stack traces for local aqua testing are apparently reporting line numbers in .js files, not in .ts files.  Did aqua not received the same source-maps upgrade as CT?
> 
> Put a failing assertion in a .ts file, run in aqua.  I’m making major changes to RectangularRadioButtonGroup.ts, and here’s what I see:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/679486/177643331-d3673ae4-e485-47bc-b23d-b746737a95f4.png">

**Comment by pixelzoom** [comment]
Confirmed - it's working great, thanks!
