### ISSUE TITLE
CT isn't finishing columns

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#158]
Related to https://github.com/phetsims/tasks/issues/1106.
@KatieWoe 
> Does anyone know why CT doesn't seem to be doing all it's tests? Should I make an issue or is it already being looked at?

@kathy-phet 
> @jonathanolson - Can you take a look at this?

@jonathanolson 
> Will do!

Kathryn Woessner
> Thanks

@samreid 
> Now that we have CTQ, should we change standard CT so that it doesn’t go to the next column until it fully finishes the current column?  Or allow column interruption during business hours but not overnight?

Kathryn Woessner
> I'm not sure it's an issue of time. They aren't getting close to completed even over the weekend

Jonathan Olson
> (Looking into it)

Sam Reid
> If you click on the column headers, it shows what commit interrupted a column.  There were a lot of commits over the weekend.

Then in another thread:

@marlitas 
> It’s really nice that CT looks only green right now, but I’m skeptical… are the greyed out cells supposed to be red? I see no info when hovering over them… is this related to: https://phetsims.slack.com/archives/C03D6JMPAHF/p1662156789059609?

Sam Reid
> I think gray means “I didn’t have time to run that test.” (edited) 

Marla Schulz
> Gotcha. Okay so does seem to be related to the issue 

Kathryn Woessner
> And if it's light green, only some of them ran, not all.

Sam Reid
> I saw there were 9 hours between 2 columns last night, but it still looks like that column had low coverage.  9/6/2022 7:56:43pm

**Comment by samreid** [comment]
Columns have been finishing lately!  But I don't see any recent aqua commits.  @jonathanolson any idea what changed here?

**Comment by jonathanolson** [comment]
I restarted the clients with `pm2 restart continuous-client` at @zepumph's recommendation, and it worked nicely.

**Comment by samreid** [comment]
Thanks, I added that to the documentation and I will close this issue.
