### ISSUE TITLE
Why is CT doing `&fuzz&stringTest=xss` ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#159]
In https://github.com/phetsims/equality-explorer/issues/189, I received a report that this test is failing CT:

```
equality-explorer : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663758258345/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1663758258345%22%2C%22timestamp%22%3A1663766095894%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
```

From the [QA Book]():
> * ?stringTest=xss: cross site scripting
>     * This query parameter puts JavaScript into every string. The page should not redirect.
>     * If the simulation does not redirect to another website, the simulation passes this test.
>     * If the simulation crashes or fails to load, the simulation still passes this test. 

Why is CT doing a fuzz test for `stringTest=xss`?

Why is CT doing `stringTest=xss` at all? Can it detect if the page has redirected?

**Comment by chrisklus** [comment]
From 11/22/22 dev meeting:

>Why is CT doing stringTest=xss at all? Can it detect if the page has redirected?

@jonathanolson: We have this test in general because it shouldn't crash, shouldn't redirect, and should look reasonable. This test runs on CT because CT will detect if the sim crashes or redirects. It's also a longer stringTest than `stringTest=long`, so may catch other layout issues that hadn't been hit before.

Back to @pixelzoom for a PSA and close.

**Comment by samreid** [comment]
Some RichText are not created during the startup sequence

**Comment by pixelzoom** [comment]
I see, that makes sense.

@KatieWoe please update the QA Book.  It currently instructs QA to start only start the sim.  Apparently a fuzz test is required.

**Comment by KatieWoe** [comment]
QA book updated and change announced on Slack.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  Looks like we're done here, so closing.
