### ISSUE TITLE
Add a single phet-io API check to quick CT

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/aqua#160]

**Comment by jonathanolson** [comment]
GAO + ph-scale should have decent coverage

**Comment by zepumph** [comment]
Perhaps also tagging @chrisklus because I know he has been working on CTQ recently. Perhaps he has bandwidth for this.

**Comment by zepumph** [comment]
@KatieWoe just reported a CT problem again:

>Several issues are showing Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

I'd like to add this to the iteration.

**Comment by zepumph** [comment]
A non zero exit code will be important for this, see above.

**Comment by zepumph** [comment]
Ok. This has been added. I ran into trouble on sparky because I didn't support npmUpdate in density. Closing
