### ISSUE TITLE
Keep aqua on master for CT

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#165]
From https://github.com/phetsims/aqua/issues/157, @jonathanolson and I would like to do this so that we can keep the aqua codebase up to date (like with lint). It is possible that undo changes would be put on master, but we can patch those up just as well as we are currently doing for lint.

**Comment by zepumph** [comment]
@jonathanolson this has been implemented and I restarted ct and ctq on bayes. Please review and feed free to close.

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
