### ISSUE TITLE
Continuous testing fails on new repo not checked out

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/aqua#18]
Should it be able to check out new repos on its own, or just ignore them and flag an error until it is updated?

**Comment by samreid** [comment]
@jonathanolson does the preceding commit fix this issue?  If not, does this issue relate to https://github.com/phetsims/aqua/issues/29#issuecomment-350071160 ?

**Comment by pixelzoom** [comment]
This happened again this past weekend and took probably 2 person-hours to figure out what was going on.  If CT can't check out the repo on its own, it should be robust enough to at least continue without crashing.

**Comment by samreid** [comment]
Flagging for dev meeting to discuss/prioritize/assign.

**Comment by samreid** [comment]
As documented in https://github.com/phetsims/wave-interference/issues/361#issuecomment-478270384, Bayes CT automatically picked up the new public waves-intro repo without requiring any effort.  @pixelzoom can you describe the problem from March 23?  Was it a private repo?

**Comment by pixelzoom** [comment]
March 23 was apparently the problem that occurred when number-line-integers was added as a non-phetsims repo, and then added to active-repos.  So as far as CT was concerned, number-line-integers didn't exist.  From Slack dev-public 3/23/19:

> Matt Pennington [10:18 AM]
All builds are currently failing because number-line-integers is in active-repos but is not actually a repo

**Comment by jonathanolson** [comment]
So is the main problem that CT fails if something is put in active-repos which isn't a repo?

**Comment by pixelzoom** [comment]
I'm guessing that the original problem was that CT failed if something in active-repos wasn't in its working copy.  Looks like that was fixed by adding a `git  clone` on 5/9/17 (!!) and is working.  But if the `git clone` fails because the repo doesn't exist, then CT fails.

**Comment by jbphet** [comment]
In today's dev meeting, we decided to just update the new sim checklist to have the developer check that a new repo was created correctly by running `clone-missing-repos`.

**Comment by pixelzoom** [comment]
Here's the modified line in [new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md):

> Add to perennial/data/active-repos, run `clone-missing-repos.sh`  to check your change, commit and push. 

Closing.
