### ISSUE TITLE
/test-result should use body for data

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#189]
Over in https://github.com/phetsims/phet-io/issues/1944, the PhET-iO team saw that we sometimes get false positives on CT because the URI of the error is too long to report. We should use request.body to fix the problem.

**Comment by zepumph** [comment]
I'm pretty sure that this is working. I got it supporting the request body for the node reporting and in continuous loop. I added back in all tests and I'll check back in tomorrow.

**Comment by zepumph** [comment]
This has been working really well. @jonathanolson can you please review and feel free to close.

**Comment by jonathanolson** [comment]
Why message.slice in https://github.com/phetsims/aqua/commit/dd15a63de7a3c7eb384458e6a1e64a3b4ba261a4? That seems like it could cut off important information.

**Comment by jonathanolson** [comment]
Switching to POST sounds great, cursory review looks good.

**Comment by zepumph** [comment]
The slice was just for the message logging because it was proving to be harder to debug with such large messages. I can revert now that we aren't iterating as much.

**Comment by samreid** [comment]
@zepumph agreed this is ready to close, thanks!
