### ISSUE TITLE
fuzz-lightyear should support running phet-io wrappers

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#190]
This is blocking migration work because it is untenable to use only CT to report the problems we are encountering.

**Comment by zepumph** [comment]
- [ ] I also got the go ahead to remove broken and old code from test-server related to local builds. This hasn't worked in a long time and likely wouldn't be the starting point for this feature in the future.

**Comment by zepumph** [comment]
I am so happy now that we removed the build related logic. Now we get much better highlighting when we succeed. 
![image](https://github.com/phetsims/aqua/assets/6856943/48ca01df-42ae-42c5-a287-db55f66a6e66)

I would like to ask @samreid about what wrappers we might want to support here. Right now it is just migration and studio.

**Comment by zepumph** [comment]
- [ ] Support state wrapper
- [ ] Rename testDuration in its current form to "timeout"
- [ ] Add a new implementation for testDuration that only starts the timer once we are loaded.

**Comment by zepumph** [comment]
I would like to do a couple more things here:

- [ ] PSA on slack
- [ ] Bring to dev meeting so people are aware
- [ ] Give this a new name. Right now it is called `test-server`. It isn't a server anymore, and I think we can do better:
* super-fuzzer
* local-fuzzer
* fuzz-master
* fuzzer-extraordinare

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
Here is the existing TODO:

```ts
              // TODO: some older sims don't support ?wrapperContinuousTest and so we are loaded if just the first goes. https://github.com/phetsims/aqua/issues/190
              // To also support the basic 'load' event to match the language of the sims
              window.parent && window.parent.postMessage( JSON.stringify( {
                type: 'load',
                url: window.location.href
              } ), '*' );
```

I'm not really sure how it should be addressed.

**Comment by zepumph** [comment]
I think if we MR'd support for `continuous-test-wrapper-load` for the oldest of our migration support wrappers then we would be able to solve this todo (getting rid of this postMessage) AND potentially fix the issue we have a better solution for https://github.com/phetsims/phet-io-wrappers/issues/507. At the very least, perhaps we should rely on wrapperContinuousTest as a parameter for the migration wrapper to squeeze out load events from both studio versions. That way we never ask for an upstream state prematurely.

**Comment by zepumph** [comment]
Discussed with @jbphet @samreid. While we are at it, we should make sure to rewrite the `migrate.js` code to always listen to the wrapperContinuousTest logic to achieve the "have both studios loaded". Perhaps we should have an MR for it and create a new issue.

**Comment by zepumph** [comment]
This will be done in https://github.com/phetsims/phet-io-wrappers/issues/507, closing.
