### ISSUE TITLE
Allow linting of all aqua files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#193]
Some source code files are currently not linted, because they include `/* eslint-disable */` for the entire file. This should be addressed so that those files can be linted.

**Comment by zepumph** [comment]
I'll hit this while working on https://github.com/phetsims/aqua/issues/205.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by zepumph** [comment]
Shoot dang, looks like trouble in PatientMultiSnapshotComparison too. I'll see if we even use this anymore.

**Comment by zepumph** [comment]
@jonathanolson and I want to delete PatientMultiSnapshotComparison.
