### ISSUE TITLE
Bayes is crashing quite a bit recently

### ISSUE THREAD

**Issue by phet-steele** [phetsims/aqua#21]

**Comment by jonathanolson** [comment]
Fixed one cause, and I've moved Chrome processes to a 2-hour loop (SHOULD restart the process every 2 hours).

The lack of timestamps in the error logs is getting annoying. If it's trouble one more time, I'll figure out a way to add them.

@phet-steele, let me know if you see any other anomalies.

**Comment by phet-steele** [comment]
There was one more commit to address this (https://github.com/phetsims/aqua/commit/71baa0ecd64344bfe5c6d65c2935ae6411732948). Since then I haven't seen a crash, so closing. Chances are I just jinxed it.
