### ISSUE TITLE
Delete many old and unused files

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#221]
It is hard to do an issue like https://github.com/phetsims/perennial/issues/372 in aqua because it feels like there is a lot of code in this repo that isn't actually used anymore, and instead is just old and unmaintained.

**Comment by zepumph** [comment]
My opinions on what to delete are in TODOs.

**Comment by zepumph** [comment]
@samreid and I like deleting js/local/.

Assigning to @samreid to do, and also to explore if there is anything that I missed.

**Comment by samreid** [comment]
I removed many unused files. 
`puppeteerCTClient.js` looks used in ContinuousServerClient. Should we keep it, and by extension, keep playwrightCTClient?

**Comment by zepumph** [comment]
Lets delete ContinuousServerClient too.
