### ISSUE TITLE
ContinuousServer had buggy snapshot deletion

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/aqua#229]
https://github.com/phetsims/aqua/commit/f0e2aee88387b8eacb3d5109224878bde26dffa8 I believe should work around part of it.

It was looping deletions of the freshly-created snapshot.

@zepumph requested creation of issue to track.

**Comment by zepumph** [comment]
Thanks for the bug fix and sorry for the trouble. From my refactor in https://github.com/phetsims/aqua/commit/becee8bfe0e0b851de0a23d719f3dda562679710. I was deleting the wrong variable. I appreciate the fix!
