### ISSUE TITLE
Color coding on continuous-report to reflect phet-io api testing

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#23]
In https://github.com/phetsims/phet-io-wrappers/issues/30 we decided it would be nice to have stable phet-io api test failures be reflected in a different color, so that they won't mess with other test failure outputs. We are not ready to implement this just yet, as we don't yet know exactly how the stable api will look, nor the stable api test. But I will let @jonathanolson know when we are ready to implement this feature. On hold for now.

**Comment by zepumph** [comment]
unassigning for now until we have a need for this (more sims with stable apis).

**Comment by pixelzoom** [comment]
@zepumph is this issue still relevant?  continuous-report doesn't exist.  And does CT still have "stable phet-io api test failures"?

**Comment by zepumph** [comment]
I don't think so. Thanks for the ping!
