### ISSUE TITLE
QUnit should not rely on timeout--it should know when tests complete

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#25]
@jonathanolson surmised that QUnit 1.14 and possibly QUnit 2.0.1 don't send out messages when testing is complete, and that aqua is having to rely on the 40 second timeout before assuming tests are complete.  

I tried setting the duration to 400,000 and ran the tests, and never saw the [next test] message when running http://localhost/aqua/html/qunit-test.html?url=http://localhost/scenery/tests/qunit/unit-tests.html

This suggests that the 40 seconds timeout is what is ending the tests.  We should try to find a way to send a message when the QUnit tests truly complete.  Related to https://github.com/phetsims/chipper/issues/624

**Comment by samreid** [comment]
According to the docs, `QUnit.done` is supposed to work here, and I see many occurrences of 
```js
  QUnit.done( function( details ) {
    window.parent && window.parent.postMessage( JSON.stringify( {
      type: 'qunit-done',
      failed: details.failed,
      passed: details.passed,
      total: details.total
    } ), '*' );
  } );
```
throughout our project.  Are these doing anything?  I tried adding this line of code to the callback:

```js
console.log('passed so far',details.passed,'/',details.total);
```
and I saw this is incremental after each QUnit.test, not after all tests completed:

```
unit-tests.html:70 passed so far 2 / 2
unit-tests.html:70 passed so far 24 / 24
unit-tests.html:70 passed so far 51 / 51
unit-tests.html:70 passed so far 143 / 143
unit-tests.html:70 passed so far 495 / 495
unit-tests.html:70 passed so far 511 / 511
unit-tests.html:70 passed so far 519 / 519
unit-tests.html:70 passed so far 837 / 837
unit-tests.html:70 passed so far 2538 / 2538
unit-tests.html:70 passed so far 2539 / 2539
```

Maybe we should try QUnit.moduleDone: https://api.qunitjs.com/callbacks/QUnit.moduleDone 
More about modules here: https://api.qunitjs.com/QUnit/module

**Comment by samreid** [comment]
It looks like scenery already defines multiple modules, and QUnit.moduleDone gets multiple callbacks per module:

```
passed so far in  Scenery: Scene 40 / 40
unit-tests.html:70 passed so far in  Scenery: Shapes 1 / 1
unit-tests.html:70 passed so far in  Scenery: Shapes 1 / 1
```

**Comment by samreid** [comment]
https://api.qunitjs.com/callbacks/QUnit.on says we should use 

```js
QUnit.on( "runEnd", function( data ) {
  console.log( "Passed: " + data.testCounts.passed );
  console.log( "Failed: " + data.testCounts.failed );
  console.log( "Skipped: " + data.testCounts.skipped );
  console.log( "Todo: " + data.testCounts.todo );
  console.log( "Total: " + data.testCounts.total );
} );
```
which according to https://github.com/js-reporters/js-reporters

> Indicates the end of a testsuite, triggered just once.

However, this doesn't seem to exist in qunit-1.14.0.js which scenery was using.  Tomorrow we'll look at upgrading QUnit and testing `on('runEnd')`

**Comment by samreid** [comment]
Query String Machine is using qunit-2.0.1.js and QUnit.on is still undefined.  According to https://github.com/qunitjs/qunit/commit/f48072e6203c9b0fc9371734cc6798de17faf28e#diff-4607e46b15da8ae44c4b47730c6d5963 on was added in Jan of 2017, just before 2.2.0, so we would need a newer QUnit.

**Comment by samreid** [comment]
I added QUnit 2.4.1 to sherpa and tested `QUnit.on( "runEnd")` in the context of Query String Machine (with added modules) and it seemed to behave correctly.  We will need to test it on asynchronous tests too.

**Comment by samreid** [comment]
Here's the compatible done listener:

```js
  QUnit.on( 'runEnd', function( data ) {
    window.parent && window.parent.postMessage( JSON.stringify( {
      type: 'qunit-done',
      failed: data.testCounts.failed,
      passed: data.testCounts.passed,
      total: data.testCounts.total
    } ), '*' );
  } );
```

**Comment by samreid** [comment]
This will be handled in qunit-connector.js when the time is right.

**Comment by samreid** [comment]
qunit-connector.js knows when the test end and is sending out the next-test message promptly.  I tested this with http://localhost/aqua/html/qunit-test.html?url=http://localhost/scenery/scenery-tests.html

@jonathanolson do we need to leave the timeout in as a "just in case tests get into loop" sort of situation?  Or should we eliminate it?  Maybe there is already a better failsafe in aqua?

**Comment by pixelzoom** [comment]
@ariel-phet can you decide how to proceed?  Waiting on a reply from @jonathanolson since 12/1/2017.

**Comment by jonathanolson** [comment]
> @jonathanolson do we need to leave the timeout in as a "just in case tests get into loop" sort of situation? Or should we eliminate it? Maybe there is already a better failsafe in aqua?

We would need to keep some form of timeout, as we wouldn't want all of e.g. CT to be stalled out by a single test.

**Comment by samreid** [comment]
In https://github.com/phetsims/aqua/commit/6d6427bf033ca245ae8c2cd0f39072cf782a999e the test duration was increased to 400000 and it seems tests now know when they have ended.  Closing.
