### ISSUE TITLE
Port from qunit-1.14.0.js to qunit-2.4.1.js

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#26]
I'm seeing usages in:

- [x] axon
- [x] dot
- [x] kite
- [x] phet-core
- [x] phetcommon
- [x] scenery

I'll use the chipper generate-test-harness branch until review and merge to master is complete: https://github.com/phetsims/chipper/issues/631

**Comment by phet-steele** [comment]
@samreid I believe one of the above commits is causing other repos to fail with the below error (since the path changed?):

```
kite : unit-tests : require.js
86 out of 87 tests passed. 1 failed.
undefined: global failure failed:
Uncaught ReferenceError: runAxonTests is not defined
https://bayes.colorado.edu/continuous-testing/snapshot-1512056319705/kite/tests/qunit/unit-tests.html:69
```

Relavent line in kite: 
```js 
runAxonTests( '../../../axon/tests/qunit' );
```

Also failing in dot, scenery, and of course axon.

**Comment by samreid** [comment]
Thanks, I removed the references.

**Comment by samreid** [comment]
We'll have a few more problems like the preceding one as Bayes transitions to the new unit tests.

**Comment by samreid** [comment]
Everything is now qunit-2.4.1, closing.
