### ISSUE TITLE
Run new tests on bayes

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#27]
See https://github.com/phetsims/chipper/issues/631

@jonathanolson and I discussed the proposed test harnesses and how to run it in Bayes.  @jonathanolson recommended that I work on changes to continuous-server.js myself, but that I would need his assistance to get it running on the server.

**Comment by samreid** [comment]
I added the entry point above, @jonathanolson can you please test that I've done it correctly?  If all seems well, can you integrate this code to run on the continuous server?  If this works out, we can remove "axon" from the preceding section `// Unit tests (require.js mode)`

**Comment by jonathanolson** [comment]
Just checked quickly, but noticed a few things:

- Can the parenthesis formatting regressions be fixed?
- I see `axon-test.html` checked in to axon, but this would load `axon-tests.html` (plural)

Otherwise it looks fine.

**Comment by samreid** [comment]
The new tests are running on Bayes, closing.
