### ISSUE TITLE
New QUnit tests should also test compiled code

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#28]
We will need a way to build and run the tests, it's a new requirejs config and main file.

**Comment by samreid** [comment]
We may also want this to be different for repos with different build system (kite, dot, scenery).

**Comment by samreid** [comment]
@jonathanolson I'd love to chat with you about this when you have time.

**Comment by samreid** [comment]
I'm going to elevate priority based on a discussion I had with @jonathanolson on slack.

Some notes:
1. Previously, dot/kite/scenery were built (without test code being built), then non-built test code was used to run the tests.
2. The new test strategy uses requirejs and it seems tricky to segregate the requirejs unit tests from the module (the code we want to test) itself.
3. Perhaps what we need is a new grunt task `grunt build-tests` which will run the requirejs build on the module but with the tests config file instead of the main config file.  This will build the module together with the tests and we can use the built tests to test the built module.  This seems like it would work great for simulations, but is different than the previous built testing strategy for kite/dot/scenery and hence @jonathanolson and I should discuss it and see if it will work or if we need to investigate a plan b.

**Comment by samreid** [comment]
I experimented with doing a "built tests" version of axon and ran into difficulties.  I thought it would be as simple as:
1. pointing chipper's requirejs build to the new config file and main
2. add QUnit to the dependencies

However, I forgot that chipper would require a title string to be declared and used.  After I added that, I saw a splash screen that never finished loading.  I'm not sure what's wrong.

**Comment by jonathanolson** [comment]
> However, I forgot that chipper would require a title string to be declared and used. After I added that, I saw a splash screen that never finished loading. I'm not sure what's wrong.

Are you looking at chipper 2.0 branch, or master?

**Comment by samreid** [comment]
I have been looking at master, knowing we would have to integrate with 2.0.

@jonathanolson and I spoke this morning and decided we will skip the built tests for now.  We haven't seen a "built-only" bug for a while so we will defer for now.

**Comment by samreid** [comment]
I removed the built tests, @jonathanolson can you please spot check review and restart Bayes testing if it seems good?

**Comment by jonathanolson** [comment]
> @jonathanolson and I spoke this morning and decided we will skip the built tests for now. We haven't seen a "built-only" bug for a while so we will defer for now.

I meant only scenery/kite/dot. I think we do still occasionally see built sim issues. That looks like it was removed (I restarted on bayes).

**Comment by samreid** [comment]
Creating compiled tests may be easier if we can combine the config files as suggested in #30.

**Comment by samreid** [comment]
On hold until we address https://github.com/phetsims/chipper/issues/638

**Comment by samreid** [comment]
It could be easy to add back the built-sim fuzz tests.  More work to add built tests for qunit (would need another build step using the qunit config file).  @jonathanolson can I double check on your recommendation before I proceed?

**Comment by jonathanolson** [comment]
> It could be easy to add back the built-sim fuzz tests.

I believe I did this as part of semi-related work.

> More work to add built tests for qunit (would need another build step using the qunit config file).

Probably not terribly important, most things would get caught in sim fuzzing for common repos.

**Comment by samreid** [comment]
Sounds good, it seems this issue is ready to close (please reopen if you disagree).
