### ISSUE TITLE
Review how to create and run new unit tests

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#29]
At today's meeting @jbphet asked if developers should be in the loop about how to use the new qunit testing, and I suggested we should discuss it at developer meeting.

Briefly, to add unit tests to a new repo:
```
cd repo
grunt generate-test-harness
touch js/{{REPO}}-tests.js
```
Then populate js/{{REPO}}-tests.js with tests, see `dot/js/dot-tests.js` for a good example, which looks like this:

```js
// Copyright 2017, University of Colorado Boulder

/**
 * Unit tests for dot. Please run once in phet brand and once in brand=phet-io to cover all functionality.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( function( require ) {
  'use strict';

  // modules
  require( 'DOT/BinPackerTests' );
  require( 'DOT/Bounds2Tests' );
  require( 'DOT/ComplexTests' );
  require( 'DOT/DampedHarmonicTests' );
  require( 'DOT/Matrix3Tests' );
  require( 'DOT/MatrixOps3Tests' );
  require( 'DOT/UtilTests' );
  require( 'DOT/Transform3Tests' );
  require( 'DOT/LinearFunctionTests' );
  require( 'DOT/Vector2Tests' );

  // Since our tests are loaded asynchronously, we must direct QUnit to begin the tests
  QUnit.start();
} );
```

Tests should be placed adjacent to the file they test (if applicable), like Vector2Tests.js is adjacent to Vector2.js.  For completeness, here is Vector2Tests.js

```js
// Copyright 2017, University of Colorado Boulder

/**
 * Vector2 tests
 *
 * @author Jonathan Olson (PhET Interactive Simulations)
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( function( require ) {
  'use strict';

  // modules
  var Vector2 = require( 'DOT/Vector2' );

  QUnit.module( 'Vector2' );

  function approximateEquals( assert, a, b, msg ) {
    assert.ok( Math.abs( a - b ) < 0.00000001, msg + ' expected: ' + b + ', result: ' + a );
  }

  QUnit.test( 'distance', function( assert ) {
    approximateEquals( assert, new Vector2( 2, 0 ).distance( Vector2.ZERO ), 2 );
    approximateEquals( assert, new Vector2( 2, 0 ).distanceSquared( Vector2.ZERO ), 4 );
    approximateEquals( assert, new Vector2( 4, 7 ).distance( new Vector2( 6, 9 ) ), 2 * Math.sqrt( 2 ) );
    approximateEquals( assert, new Vector2( 4, 7 ).distanceSquared( new Vector2( 6, 9 ) ), 8 );
  } );
} );
```

To add a new repo for testing on Bayes, add it to the list in `continuous-server.js` which is currently:

```js
// repo-specific Unit tests (require.js mode) from `grunt generate-test-harness`
[ 'axon', 'circuit-construction-kit-common', 'dot', 'kite', 'phetcommon', 'phet-core', 'phet-io', 'query-string-machine', 'scenery' ].forEach( function( repo ) {
```

Then make a request to @jonathanolson to restart bayes.  The tests automatically run on Bayes with the following query parameters:
```js
'', '?ea', '?brand=phet-io', '?ea&brand=phet-io'
```

**Comment by jonathanolson** [comment]
Instead of having me restart bayes, we would create another list under perennial/data that would be all of the sims with `${repo}-tests.html` that should be run. This would be updated whenever you add unit tests to a sim, and continuous testing would pull the data file and add it to the tests (without restarting).

**Comment by jonathanolson** [comment]
Assigning to me for the above, unless anyone has objections.

**Comment by jonathanolson** [comment]
Should be done, referencing the generated perennial/data/unit-tests, which is generated from the `phet.generatedUnitTests` in package.json. The other work was done previously, and updated docs above.
