### ISSUE TITLE
How to deal with assert.expect( 0 )?

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#31]
In https://github.com/phetsims/aqua/issues/30 we discussed `assert.expect`.  Here's a case where it's used and currently necessary:

```js
// Copyright 2017, University of Colorado Boulder

/**
 * QUnit Tests for BooleanProperty
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( function( require ) {
  'use strict';

  // modules
  var BooleanProperty = require( 'AXON/BooleanProperty' );

  QUnit.module( 'BooleanProperty' );
  QUnit.test( 'BooleanProperty', function( assert ) {
    window.assert && assert.throws( function() {
      new BooleanProperty( 'hello' ); //eslint-disable-line
    }, 'invalid initial value for BooleanProperty' ); // eslint-disable-line
    var c = new BooleanProperty( true );
    c.set( true );
    c.set( false );
    c.set( true );
    window.assert && assert.throws( function() {
      c.set( 123 );
    }, 'set an invalid value for BooleanProperty' );

    if ( !window.assert ) {
      assert.expect( 0 );
    }
  } );
} );
```

When assertions are enabled, two tests are run (the assert.throws calls).  When assertions are disabled, 0 tests are run.  If the `assert.expect` was commented out, QUnit would report a failure with this message: 

> Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.

Two solutions for dealing with this problem are:
1. Use `assert.expect(0)` as we have been
2. Add a different assert test, such as `assert.ok( c.value, 'boolean value should be true' );` which runs whether assertions are enabled or not.

(1) would fail if we add a test like (2).  But (2) seems like a bit of a workaround to deal with QUnit expecting at least one test by default.  @pixelzoom which do you recommend?

**Comment by pixelzoom** [comment]
Why do we need to run unit tests with assertions disabled?

**Comment by samreid** [comment]
It may be unnecessary to run unit tests with assertions disabled.  Is there a class of errors that only manifests when assertions are off?  If so, is it a frequent enough kind of error that we need to run tests with assertions disabled?

**Comment by pixelzoom** [comment]
>  Is there a class of errors that only manifests when assertions are off? If so, is it a frequent enough kind of error that we need to run tests with assertions disabled?

The only one I can think of is failure to use `assert &&` before a call to `assert`.  And that will certainly be noticed outside of unit tests.

**Comment by samreid** [comment]
The proposal to only run unit tests with assertions enabled sounds reasonable to me, but I want to run it past @jonathanolson before we proceed.

**Comment by pixelzoom** [comment]
If you're going to use this pattern:

```js
    if ( !window.assert ) {
      assert.expect( n );
    }
```

... then you shouldn't be assuming that there are n tests that don't involve `window.assert`.  You should be keeping a counter that gets incremented whenever any test is run, then check the counter:

```js
assert.expect( numberOfTestsRun );
```

And yes, that sounds like a colossal error-prone pain.

**Comment by pixelzoom** [comment]
If we do decide to run tests with assertions enabled, then tests should verify that `assert` is enabled.

**Comment by samreid** [comment]
We are also planning to run unit tests on compiled code, where assertions cannot be enabled.

**Comment by jonathanolson** [comment]
> We are also planning to run unit tests on compiled code, where assertions cannot be enabled.

Presumably only for scenery/kite/dot, not the simulations/runnables?

**Comment by samreid** [comment]
I'm getting confused.  In this thread: https://github.com/phetsims/aqua/issues/28#issuecomment-350433763

>> @jonathanolson and I spoke this morning and decided we will skip the built tests for now. We haven't seen a "built-only" bug for a while so we will defer for now.

> I meant only scenery/kite/dot. I think we do still occasionally see built sim issues. That looks like it was removed (I restarted on bayes).

Did you mean "We will only skip scenery/kite/dot and will continue to test built sims, since we see issues there"?

**Comment by pixelzoom** [comment]
Sam Reid [10:31 AM]
We could avoid the assert.expect() altogether if we add at least one non-short-circuited assert.* call to each test.  Should we do that too?

Chris Malley [10:32 AM] 
I think having a “dummy” test that is always run and succeeds is preferrable to having assert.expect(0).   But surely someone else must have run into this problem….

**Comment by pixelzoom** [comment]
`assert.ok( true, 'so we have at least 1 test in this set' );`

**Comment by pixelzoom** [comment]
@jonathanolson I assume that this is also unnecessary in TrailTests.js:

```js
680    // this may change if for some reason we end up calling more events in the future
681    assert.expect( 4 );
```

OK to remove it?

**Comment by samreid** [comment]
In TrailTests.js the `assert.expect( 4 )` is checking that exactly 4 of the preceding 6 callbacks were called--it may be necessary (though I must admit I don't understand why we would only expect 4 of those 6 callbacks).

**Comment by samreid** [comment]
Mind if I replace all `assert.expect( 0 )` with `assert.ok( true, 'so we have at least 1 test in this set' );`?  I wasn’t sure if you are working on it or not.

**Comment by samreid** [comment]
@pixelzoom gave me the go-ahead on slack

**Comment by samreid** [comment]
I replaced `expect( 0 )` with the synthetic test.

**Comment by samreid** [comment]
@pixelzoom can I create a scenery issue for https://github.com/phetsims/aqua/issues/31#issuecomment-350799249 and close this issue?

**Comment by samreid** [comment]
I created https://github.com/phetsims/scenery/issues/720, closing.
