### ISSUE TITLE
document query parameters in test-sims.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#32]
A Slack discussion today (12/11/17) pointed someone to the `testSims` query parameter in test-sims.js.  I was surprised to see that none of the query parameters in test-sims.js are documented. I.e.:

```js
 var options = QueryStringMachine.getAll( {
    testTask: {
      type: 'boolean',
      defaultValue: true
    },
    testRequirejs: {
      type: 'boolean',
      defaultValue: true
    },
    testBuilt: {
      type: 'boolean',
      defaultValue: true
    },
    testDuration: {
      type: 'number',
      defaultValue: 30000 // ms
    },
    testSims: {
      type: 'array',
      defaultValue: [], // will get filled in automatically if left as default
      elementSchema: {
        type: 'string'
      }
    },
    testConcurrentBuilds: {
      type: 'number',
      defaultValue: 1
    }
  } );
```

**Comment by pixelzoom** [comment]
The one bit of documentation in the above:

` defaultValue: [], // will get filled in automatically if left as default`

... leaves me with the question "filled in automatically using what?"

**Comment by jonathanolson** [comment]
Is the documentation in the above commit sufficient?
