### ISSUE TITLE
Move phettest to a new machine

### ISSUE THREAD

**Issue by phet-steele** [phetsims/aqua#33]
The main motivation is to speed up phettest. It would be great if the "Pull All" button could use `parallel-pull-all.sh`, but the current machine serving phettest (Mendeleev) can't handle that. (I'd need @jonathanolson's help on wiring that button up after switching machines) 

Oh and the header for phettest would have to change to a new name, whatever that may be:

<img width="707" alt="screen shot 2017-12-13 at 11 01 27 am" src="https://user-images.githubusercontent.com/5863899/33954308-23a0cd1e-dff5-11e7-9f57-a82eb08a4bd7.png">

**Comment by jonathanolson** [comment]
Presumably I can help wire it up tomorrow. Do you have a computer selected?

**Comment by phet-steele** [comment]
> Presumably I can help wire it up tomorrow. Do you have a computer selected?

Tomorrow sounds great. I've selected a new-ish MacBook Pro running macOS 10.13.2. `parallel-pull-all.sh` runs great on it.

**Comment by phet-steele** [comment]
Work on the transfer is over, thanks @jonathanolson
