### ISSUE TITLE
document how to restart Continuous Testing (CT) service 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#35]
As reported on Slack, Continuous Testing server (aka aqua, aka bayes) has been down for several days during the week of 12/25, and is still down as of this writing.  Since PhET has come to rely on this, perhaps we should have some instructions on how to start it.  @jonathanolson is apparently running it  from his own account, and it's questionable whether https://github.com/phetsims/aqua/README.md is sufficient or up-to-date.

**Comment by pixelzoom** [comment]
In Slack dev-public:

----- December 27th, 2017 -----
Sam Reid [9:14 AM] 
Bayes has been blank for a few days now.

----- December 28th, 2017 -----
Chris Malley [10:03 AM] 
Bayes is still down. Anyone on it?

Chris Malley [10:08 AM] 
Are the instructions for restarting bayes in https://github.com/phetsims/aqua/README.md? Are they current? @jonathanolson?

Sam Reid [10:09 AM] 
Last we spoke he said he runs the process under his account and it is not set up for others to restart it.

I’ve been relying on aqua/local testing for the last few days

**Comment by ariel-phet** [comment]
Also marking for dev meeting for the moment, since there might be some auxiliary questions

**Comment by jonathanolson** [comment]
As discussed in Slack chat, I'll need a new GitHub account for this purpose (or shared with other automated purposes).

https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users notes that we can just create an account (ideally with a phet admin email account, @oliver-phet are you available to do this?), and then we can assign it as an outside collaborator.

Tagging @jbphet, as he noted rosetta would ideally use this type of account also.

Additionally, before creating the account(s), we should decide if we want one account per purpose (one for rosetta, one for continuous testing, etc.), or if one account total would be fine (continuous testing doesn't ever need write permissions).

**Comment by oliver-phet** [comment]
@jonathanolson I just created a new account, I'll slack credentials.

**Comment by jbphet** [comment]
The related issue for rosetta is https://github.com/phetsims/rosetta/issues/168.

**Comment by jonathanolson** [comment]
Added relevant documentation in https://github.com/phetsims/aqua/blob/master/docs/continuous-testing-management.md.

@ariel-phet, should someone review this?

**Comment by pixelzoom** [comment]
Assigned to me at 1/4/18 dev meeting.  I'll review, then have @jonathanolson shut down CT and see if I can successfully restart it.

**Comment by pixelzoom** [comment]
Starting to walk through the documentation...

[continuous-testing-management.md](https://github.com/phetsims/aqua/blob/master/docs/continuous-testing-management.md) says to use `pm2 list` to display running processes.   I see data at https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-report.html, but `pm2 list` does not show "App name" `continuous-server`, or any other processes. @jonathanolson can you please clarify?  Here's what I see:

```
% pm2 list
┌──────┬──────┬────────┬───┬─────┬────────┐
│ Name │ mode │ status │ ↺ │ cpu │ memory │
└──────┴──────┴────────┴───┴─────┴────────┘
 Use `pm2 show <id|name>` to get more details about an app
%
```

**Comment by pixelzoom** [comment]
`pm2 list` apparently only shows the processes associated with the user who runs it.  And "All continuous testing parts run on bayes.colorado.edu under the phet-admin user" apparently means that everything in the doc (not just "testing") must be run while logged in as phet-admin.

**Comment by pixelzoom** [comment]
Slack with @jonathanolson:

Chris Malley [1:49 PM] 
i’ve reviewed the entire continuous-testing-management.md doc.  There are multiple levels of failure described.  Do you think it’s sufficient to simply confirm that I can `pm2 stop continuous-server ` then `pm2 start continuous-server `?

Jonathan Olson [2:05 PM] 
That would presumably be fine
Make sure you can browse the logs for the process too
As that would happen almost every time anyone is debugging something

Chris Malley [2:08 PM] 
Does “browse the logs” === “pm2 logs”, or peruse /home/phet-admin/.pm2/logs ?

Chris Malley [2:23 PM] 
Figured it out myself… `pm2 logs` looks like it’s doing a tail of log files in /home/phet-admin/.pm2/logs/.   And if needed, I can go directly to /home/phet-admin/.pm2/logs/ to look through them.

Chris Malley [2:32 PM] 
Are you around for 15 minutes or so while I restart CT?  In case something goes wrong…

**Comment by pixelzoom** [comment]
Couldn't sync up with @jonathanolson, so this will have to wait until next week.

**Comment by pixelzoom** [comment]
I did:

```
% pm2 stop continuous-server
% pm2 start continuous-server
% pm2 list
```

After waiting 10 minutes or so, everything looks as expected on https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-report.html.

So basic stop/start is working.  If there are any more advanced admin scenarios, we'll test the documentation when we encounter them. 

Closing this issue.
