### ISSUE TITLE
Built sims aren't loading in test-sims.html

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/aqua#39]
Built sims are not loading in local tests using test-sims.html. @jonathanolson is this related to chipper 2.0? Maybe after version/id convention changes? All sims look like this:

![capture](https://user-images.githubusercontent.com/6396244/35531179-7d853bda-04f3-11e8-9fd7-a2b21091ff4c.PNG)

**Comment by jonathanolson** [comment]
Yes, I believe I missed that in the chipper 2.0 work. Checking.

**Comment by jonathanolson** [comment]
Applied fixes above. Seems to be working for me now, can you verify?

**Comment by jessegreenberg** [comment]
Looks great to me, thanks @jonathanolson 
![capture](https://user-images.githubusercontent.com/6396244/35535730-c9f0f6ea-0501-11e8-8121-fa9aeb5a8041.PNG)
