### ISSUE TITLE
removing a repository causes issues

### ISSUE THREAD

**Issue by jbphet** [phetsims/aqua#40]
The 'exemplar' repo was recently deleted, and after this happened, Continuous Testing (CT) started failing.  It wasn't just failing for the examplar repo - it was failing to update the web page at all.

I worked with @phet-steele to fix this, and we did it by shutting it down, manually deleting the local copy of the examplar directory used by CT, doing a `git pull`, and restarting CT.

Is there something that can be done to make CT handle this automatically?

**Comment by pixelzoom** [comment]
@jbphet asked:
> Is there something that can be done to make CT handle this automatically?

... or at least document what needs to be done when a repo is deleted or renamed?

**Comment by pixelzoom** [comment]
No progress on this since 2/19/2018, and it was a problem report, not a potential feature.   Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
Since this problem does not seem to have come up again, closing
