### ISSUE TITLE
Bayes CT now requires a *.js suffix to start CT?

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#42]
`pm2 start continuous-server` reports 

> script not found : /data/share/phet/continuous-testing/aqua/js/continuous-server

But adding the *.js suffix seems to be OK.  Why did this change?  Shall we update continuous-testing-management.md?

**Comment by jonathanolson** [comment]
Sorry, I updated the docs (and a few other points), and verified it. Not sure, but it's probably not worth investigation.
