### ISSUE TITLE
Bayes CT is down

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/aqua#50]
The CT page is not showing any results.
![down](https://user-images.githubusercontent.com/41024075/45887251-7ca95f00-bd78-11e8-8032-8c4ccad37e9b.PNG)

**Comment by jonathanolson** [comment]
I updated phet-io-wrapper-arithmetic's permissions and it looks like it resolved the issue. The first snapshot completed npm stuff, and it looks like the testing has started.
