### ISSUE TITLE
CT results not showing up

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/aqua#51]
As of the 3:22 PM Mountain time 10-08-2018, the last results are from 6:24 pm 10-07-2018.
Snap shot status is:
```
Snapshot status: [2018-10-8 15:22:15] Checking for commits (no changes since last snapshot)
Remaining browser tests for latest: 0
```
![ct](https://user-images.githubusercontent.com/41024075/46634419-1f4e3580-cb0e-11e8-95b0-a8c049a6f042.PNG)

**Comment by jonathanolson** [comment]
Looks like slater was removed (but not in our "list" of repositories) leading to failures. This should be fixed now, and it looks like it's creating a new snapshot at this moment.

Let me know if this isn't resolved.
