### ISSUE TITLE
Most tests undone

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/aqua#54]
If you uncollapse the tests in CT you'll see that almost all test are consistently not being done.  So the chart looks light green consistently, but under the hood very few tests are done. 12:00pm Oct 17.

**Comment by jonathanolson** [comment]
This is the second time in a row that fuzzing protein-synthesis (normal fuzzing) has crashed the last test (and may be causing the stall-out).

I've added some additional logic so that the Chrome processes will get restarted every X hours (somewhat staggered, but between 11 and 19 hours), so that we don't run into this situation in the future.

**Comment by jonathanolson** [comment]
Let's see if this stays stable for a few days (then can close).

**Comment by KatieWoe** [comment]
@jonathanolson results still look pretty sparse this morning.

**Comment by pixelzoom** [comment]
> This is the second time in a row that fuzzing protein-synthesis (normal fuzzing) has crashed the last test (and may be causing the stall-out).

Just out of curiosity... Any idea how/why?

**Comment by pixelzoom** [comment]
protein-synthesis has a massive memory leak. After < 3 minutes of fuzz testing, the heap snapshot is 790MB.

**Comment by samreid** [comment]
I set runnable to false in protein synthesis in https://github.com/phetsims/protein-synthesis/commit/a02d7e540e1f38775e2bf4e6c16d23bc0d22a68f, hopefully this resolves the problem.

**Comment by jonathanolson** [comment]
Restarted CT and Chrome processes.

**Comment by samreid** [comment]
There were a few dark green columns last night, is this issue resolved?

**Comment by KatieWoe** [comment]
Looks like for the most part @samreid.  I think the tests are being done a bit slower than they used to, but they are being done.

**Comment by jonathanolson** [comment]
It now seems like tests are still a bit slow, but are moving along. There are some memory leaks in some of the fractions code that may also be contributing, which I will have fixed up soon.

Should we keep this issue open?

**Comment by KatieWoe** [comment]
May have reoccurred 10-26-2018.  CT did not complete tests the night before, despite a few hours to do so.  Assigning to @jonathanolson to reassign as appropriate.

**Comment by jonathanolson** [comment]
Looks like things might be crashing due to running out of memory. Not sure if it's process-specific, or if the whole system is memory constrained.

It's basically down to running 1 test a minute, which is quite slow.

**Comment by jonathanolson** [comment]
Looks like individual tests might be running out of memory, crashing the browser processes and stalling things.

**Comment by samreid** [comment]
How often is the chrome process restarted during testing?  Would it help to regularly restart the chrome process after N tests?

**Comment by jonathanolson** [comment]
I'm now restarting them in a range from 1 to 9 hours (so they don't all restart at once and create testing gaps ideally).

We're not using something like puppeteer, so I can't see what is being done with tests to decide when to restart.

**Comment by jonathanolson** [comment]
I've also added test information to the page and title (of the browser tab doing the testing) so hopefully I can identify what tests are stalling things on the testing client (see https://github.com/phetsims/aqua/issues/55)

**Comment by jonathanolson** [comment]
I'm running 4 local test loops, I'll see if any crash and I can get more information.

**Comment by jonathanolson** [comment]
2 of the 4 have crashed on `unit-rates : fuzz : require.js-canvas` so far. Other two are running.

**Comment by jonathanolson** [comment]
@KatieWoe how has testing been lately?

**Comment by KatieWoe** [comment]
Its been much better than when the issue was made.  More tests are still missed than there used to be, but I think it tends to be acceptable.  Less room for error though.

**Comment by KatieWoe** [comment]
Been ok for some time, so closing if that's alright with you @jonathanolson
