### ISSUE TITLE
Tests look like they pass, but turn salmon instead of green.

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#57]
I'm seeing this locally (left) as well as on phettest (right)

![image](https://user-images.githubusercontent.com/679486/48788222-964b2200-eca7-11e8-9dae-69bbca073ff9.png)

@jbphet is testing as well.

**Comment by samreid** [comment]
@jbphet reported similar findings:

> I'm not seeing any failures in the console, but everything in the indication area looks like it's failing.

**Comment by jessegreenberg** [comment]
I think this is fixed after https://github.com/phetsims/tasks/issues/958. @samreid can you please confirm?

**Comment by samreid** [comment]
It's fixed now, thanks @jessegreenberg, closing.
