### ISSUE TITLE
Install phantomjs on simian and get it running

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#6]
See #2 and #4

**Comment by samreid** [comment]
OIT asked what we will need and I replied:

>  We would like to start with an installation of http://phantomjs.org/ and I don't know if there is already good software for scheduling recurrent tasks (could use cron but I heard there was something nicer).  We will run a node program that uses phantomjs and sends out email notifications about failures.  I suspect we already have node, not sure if we need something else to send emails from it.  We'll also need to run git but I think that may already be installed.

**Comment by samreid** [comment]
OIT replied:

2016-09-20 12:56:31 MDT - Jacob EnglemanComments
Ariel/Sam,
 
Since it sounds like the use case for simian has changed, from phet-dev to a CI server, we should re-evaluate what type of support is appropriate. If SIS continues to manage the server, we'll need to retain control of software installation and system configuration, but we can delegate some application configuration to your team. We'll also continue to monitor/patch/backup/etc. the server as is standard for hosts we manage.
 
On the other hand, if you'd like full control of the server to install software and modify system settings, it may be better to move to a consulting approach like we have done with the new phet-server and phet-cache machines. In this case, your team would be fully responsible for and in control of the server. You could then contract with us for specific needs like backups/etc.
 
Please let me know what best meets your needs, and we'll proceed down that road. I'm happy to clarify or answer any questions as well. We're still happy to install this software for you, like phantomjs, but I want to make sure we're not getting in your way.
 
Thanks.
 
-Jake

**Comment by samreid** [comment]
Ariel, Matt, Jon,

I don't feel strongly one way or the other but that's partly because I don't know all the tradeoffs with SIS server management.  That being said, it seems safe to stay with them for now because we only expect a few things to be installed in the near future.

* phantomjs
* node.js

I checked that it already has git and nano.  Presumably we could download or build our own https://nodemailer.com/

I'm running this past you first instead of responding directly to OIT so that we can discuss it beforehand. Thoughts?

Best Regards,
Sam

**Comment by samreid** [comment]
Continuing discussion on the issue mentioned above (or is it?)

**Comment by samreid** [comment]
2016-10-03 12:42:28 MDT - Dylan CanfieldComments
Matt / Sam,
Unforutnately Phantomjs cannot be built on simian because the project does not support RHEL5, and never will.
https://github.com/ariya/phantomjs/issues/12773
 
Nodejs (with npm) is installed under /usr/local/nodejs.
 
Is there anything else that I can help you with?
 
-Dylan

**Comment by samreid** [comment]
2016-10-05 10:22:42 MDT - Dylan CanfieldComments
Matt / Sam,
Given that PhantomJS won't work on RHEL5, is there an alternative piece of software that you would like to use on simian?
 
Regards,
Dylan Canfield
OIT - Shared Infrastructure Services

**Comment by samreid** [comment]
I haven't seen phantom alternatives that provide the functionality we would like.

Is there any way to upgrade GLIBCXX and GLIBC on RHEL5?  (The phantomjs page says we can use the built binary if the system has GLIBCXX_3.4.9 and GLIBC_2.7, http://phantomjs.org/download.html )

Alternatively, what options do we have for upgrading simian to a later OS?  Can simian run an VM that supports phantomjs minimum requirements?

Best Regards,
Sam

**Comment by ariel-phet** [comment]
I feel like @markmorlino might have some thoughts here since he is going to be helping us think about the architecture for Simian as DR

**Comment by ariel-phet** [comment]
@samreid feel perhaps it might be useful to talk with @markmorlino and explain the requirements

**Comment by samreid** [comment]
Greetings @markmorlino!  The requirements for phantomjs are enumerated on the download page: http://phantomjs.org/download.html

What do you recommend?

**Comment by ariel-phet** [comment]
@samreid can you also give context, I think understanding exactly the problem you want to solve would be helpful as well

**Comment by samreid** [comment]
We would like a headless browser engine (webkit or better) that can run in a continuous integration system to help us identify issues in our simulations via automated testing.

**Comment by samreid** [comment]
@markmorlino are you sure RHEL7 will provide phantom minimum requirements?  What would the steps be for updating to RHEL7?

**Comment by markmorlino** [comment]
Yes, RHEL7 meets the minimum requirements for phantomjs.
It would be a complete re-installation of the operating system: document what is installed and running on the system, backup relevant configuration and data, install new OS, install and configure applications.

**Comment by samreid** [comment]
Note to self: ask OIT what would would be involved in an upgrade, is it a clean install or do we keep data?

**Comment by samreid** [comment]
@jonathanolson needs advance notice if we are wiping the system.  @jonathanolson is also running a process (for half a month so far) that needs to be completed or terminated.

**Comment by samreid** [comment]
I emailed OIT:

 Dylan,

It appears that like RHEL 5 End of Production 3 Phase is currently set for March 31, 2017, we are wondering what would be involved in an OS upgrade?
https://access.redhat.com/support/policy/updates/errata

Best Regards,
Sam

On hold until we receive a response.

**Comment by samreid** [comment]
2016-10-06 14:56:40 MDT - Dylan CanfieldComments
Ariel,
Yes, it is possible for your group to do the upgrade yourself. However, I did not mean to imply that we were unable or unwilling to manage a system for your automated testing framework on a newer OS. I wanted to get a discussion started to see how we could most effectively provide a solution that met your requirements. If "disaster recovery" is a requirement of this rebuild, that definitely rules out a new VM as we are currently unable to run VMs in multiple locations (though we are working on that capability).
 
Also, we do have multiple OIT data-centers where we could rack systems. What are your plans for the current figaro? Would you be interested in racking it over at SPSC and leveraging it for "disaster recovery"?
 
 
Orrie,
Given the desire to fall back to this system during periods of data center downtime, do you have any suggestions?
 
Regards,
Dylan Canfield

**Comment by samreid** [comment]
We will reassign this after we have a new server.

**Comment by samreid** [comment]
Bayes is being tracked here: https://github.com/phetsims/special-ops/issues/53

**Comment by samreid** [comment]
No need for phantom, Bayes is using Chrome, closing.
