### ISSUE TITLE
Why doesn't Balloons and Static Electricity unit test fail show on Bayes CT?

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#62]
The issue here https://github.com/phetsims/balloons-and-static-electricity/issues/438 has been problematic for a while, but I don't recall ever seeing it on Bayes CT, even though continuous-server.js does list `balloons-and-static-electricity` as one of its unit test repos.

**Comment by jessegreenberg** [comment]
I was wondering if any sim unit tests are currently being run on CT and found that they are for CCK common
```js
circuit-construction-kit-common : top-level-unit-tests : require.js?brand=phet-io
13 out of 13 tests passed. 0 failed.

Approximately 12/27/2018, 11:06:52 AM
circuit-construction-kit-common : top-level-unit-tests : require.js?ea
13 out of 13 tests passed. 0 failed.

Approximately 12/27/2018, 11:06:52 AM
circuit-construction-kit-common : top-level-unit-tests : require.js?ea&brand=phet-io
13 out of 13 tests passed. 0 failed.

Approximately 12/27/2018, 11:06:52 AM
```

**Comment by jessegreenberg** [comment]
I don't know what might have changed, but confirmed they are running on CT now. Closing, will reopen if this shows up again.
