### ISSUE TITLE
include instructions on how to restart CT when aqua has been changed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#63]
https://github.com/phetsims/aqua/blob/master/doc/continuous-testing-management.md says “The server, when running, will be continually pulling every repository (with the exception of aqua itself, which it will leave on the same SHA, so that it doesn’t automatically start running new continuous server code).”  But there are no details on how/where to pull aqua on bayes.

This came up recently when aqua was changed and CT started failing `lint-everything`.

**Comment by samreid** [comment]
I think it would be something like:

1. Log in to bayes.colorado.edu as phet-admin, requires VPN.
2. cd `/data/share/phet/continuous-testing/aqua`
3. `pm2 stop continuous-server`
4. `git pull`
5. `pm2 start continuous-server`

I'll give it a try!

**Comment by samreid** [comment]
Those instructions seemed to work, I'll copy them to continuous-testing-management.md and leave this assigned to @jonathanolson to double check.

**Comment by jonathanolson** [comment]
Yup looks good, thanks!
