### ISSUE TITLE
Consider automatically testing reset all

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#67]
Inspired by https://github.com/phetsims/wave-interference/issues/321#issuecomment-456526128.  We could do the following:

1. launch a simulations with ?screens=1 or higher
2. capture screenshot
3. fuzz 20 seconds
4. search scene graph to find ResetAllButton, assert there is one result
5. trigger the reset all button
6. capture screenshot
7. assert screenshots match exactly.

This could catch cases where simulation reset all doesn't actually reset everything.  Simulations that have a startup animation, like ph scale, may not work out of the box.

**Comment by samreid** [comment]
I don't think I'll have time to work on this in the near future unless it is prioritized differently.  I'll run it past @ariel-phet to see what he thinks.  Any other developer could work on this as well.  Maybe consult with QA to see how much effort this is worth, I know it would have caught at least one problem the QA team identified in the last few months.

**Comment by ariel-phet** [comment]
@samreid I think this work can be deferred. Testing the reset is very much a staple of QA testing, and it seems like there are some edge cases (especially randomly seeded games and such) where this might run into issues. I would think it would be a fair bit of effort to get working properly, so marking as deferred.

**Comment by pixelzoom** [comment]
@ariel-phet I think it's unlikely that this will ever be automated, and QA seems to be handling this.  I recommend closing.

**Comment by ariel-phet** [comment]
@pixelzoom agreed, closing
