### ISSUE TITLE
Make it possible to run CT locally

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#69]
During #49 @jonathanolson and I discussed some ideas for getting CT to run locally as opposed to being hard-coded to run on Bayes.

(a) Right now, a single snapshot with node_modules is >5GB, so is a significant hassle to check out and run one snapshot.
(b) Right now, the server runs 8 parallel processes for `buildLoop`, this would likely slow down or impede the developer's machine
(c) If we want to set up CT to run locally for the sake of iteration & development, we would likely need to choose a subset of repos and a subset of tests to make it tractable.
(d) Another possibility in that same direction would be to set up the CT harness (client + server) with trivial or mock tests, so we could develop/debug that part in isolation.

Based on these considerations, @jonathanolson and I decided not to investigate this at the moment.  However, if we invest in #68 or other issues that require rapid iteration on this code, we may want to reconsider some of these steps.

**Comment by zepumph** [comment]
CT can run locally now! Potentially since https://github.com/phetsims/aqua/commit/f7bd04e8ca42fdda2adf9393a3de255ff96a7ad7. Closing
