### ISSUE TITLE
should rootRenderer=canvas test be removed from CT?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#75]
In https://github.com/phetsims/vector-addition/issues/33, Vector Addition was experiencing a CT problem when run with `rootRenderer=canvas`.   Since Vector Addition doesn't require Canvas explicitly, I was wondering about the purpose of this test, which is apparently run for every sim.   

@jonathanolson responded with:
> It mimics how we used to force Canvas rendering for Edge (which we now do not do, IIRC)

So should this test be removed from CT?  We don't need to be running vestigial test.

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
Seems worth removing (and should be easy to do). @jonathanolson mind removing this test?

**Comment by jonathanolson** [comment]
Removed, closing.
