### ISSUE TITLE
random "above our memoryLimit" errors appearing in CT

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#79]
CT errors like this seem to be popping up randomly:

```
balloons-and-static-electricity : accessibility-fuzzBoard : require.js : run
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Average memory used (1079MB) is above our memoryLimit (1000MB). Current memory: 1090MB.
Error: Average memory used (1079MB) is above our memoryLimit (1000MB). Current memory: 1090MB.
    at MemoryMonitor.measure (https://bayes.colorado.edu/continuous-testing/snapshot-1573286587318/joist/js/MemoryMonitor.js?bust=1573315515392:64:15)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1573286587318/joist/js/Sim.js?bust=1573315515392:243:28
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1573286587318/axon/js/Action.js?bust=1573315515392:230:20)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1573286587318/joist/js/Sim.js?bust=1573315515392:957:33)
    at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1573286587318/joist/js/Sim.js?bust=1573315515392:938:14)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1573286587318/joist/js/Sim.js?bust=1573315515392:921:14)
id: Bayes Chrome
Approximately 11/9/2019, 1:03:07 AM
```
<br>

I recall that we had a problem with this error being erroneously (and seemingly randomly) being associated with sims, but I thought that was addressed. Having to inspect these repeatedly is a little annoying -  in the current CT history, there are no fewer than 6 sims that are identified as exceeding memory limits, and I don't believe that they are.  It would be good to understand why this is happening.

Assigning to @ariel-phet to assign and prioritize.

**Comment by pixelzoom** [comment]
I said:
> ... I recall that we had a problem with this error being erroneously (and seemingly randomly) being associated with sims, but I thought that was addressed. 

This is the fix that I was thinking of, applied by @jonathanolson: https://github.com/phetsims/aqua/commit/215f25c9f1938cc0da7810a8de54e4fc86bdf372

**Comment by pixelzoom** [comment]
Slack developer channel:

Chris Malley 10:26 AM
Has anyone else noticed the annoying frequency of “above our memoryLimit” errors being reported by CT? They appear to be randomly associated with repos.  @jonathanolson is it possible that https://github.com/phetsims/aqua/issues/49 has resurfaced?

Sam Reid:house_with_garden: 10:27 AM
I’ve seen it several times lately, and have been honing my skills at ignoring it

Jonathan Olson 10:27 AM
It's possible. Maybe we have a cross-sim memory leak also?

Chris Malley 10:28 AM
I’m not sure how I ignore it without ignoring real problems. I have to look at each non-green box for my sims in CT.

**Comment by ariel-phet** [comment]
@jonathanolson is not sure if this is a memory leak in common code or one sim blowing memory, he will investigate for an hour or two to see if he can narrow down the issue.

**Comment by pixelzoom** [comment]
@ariel-phet FYI, I'm still spending a few minutes every day inspecting these false errors.

**Comment by pixelzoom** [comment]
These seems to have (mostly?) disappeared since CT was rewritten. Closing.
