### ISSUE TITLE
2 files named test-sims.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#8]
There are currently 2 files in aqua named test-sims.js.  This is confusing, recommended to rename one of them.  Assigning to @samreid since he created the second one (aqua/js/test-sims.js).

**Comment by pixelzoom** [comment]
Also recommended to document aqua/js/test-sims.js.  It currently has no documentation, so I have no idea of its purpose.

**Comment by samreid** [comment]
I added some minimal docs and renamed test-sims.js to phantom-script.js above.  We can flesh this out more if/when we devote more time to continuous integration.  @pixelzoom do you see anything else that should be done now?

**Comment by pixelzoom** [comment]
Looks good for now, closing.
