### ISSUE TITLE
Add continuous testing for other browsers

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#80]
At today's meeting, we discussed the fact that Bayes CT is only reporting testing on one version of Chrome.  We would like to extend this to cover other browsers, to catch issues like the ones that came in https://github.com/phetsims/tasks/issues/932

We discussed getting another Windows machine (not a server) that could run testing in several browsers (including IE, firefox, edge, chrome).

Assigned to @ariel-phet to discuss hardware, and to @jonathanolson to discuss if any changes need to be made to CT to know what browser was reporting.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/perennial/issues/153 we decided it would be really nice to have IE testing built sims on CT. Pinging here for potential priority boost!

**Comment by zepumph** [comment]
Another ping here because of https://github.com/phetsims/energy-forms-and-changes/issues/320. It would be really nice if we could know when changes break IE well before we get to the QA process. Adding to developer meeting to see how feasible adding IE to CT would be.

**Comment by jessegreenberg** [comment]
Was discussed on 5/21/20 - 

Issues in https://github.com/phetsims/aqua/issues/80#issuecomment-595524434 and https://github.com/phetsims/aqua/issues/80#issuecomment-601902318 were related to IE11, maybe not as important if we decide to drop that platform that often gives us issues.

**Comment by ariel-phet** [comment]
Considering that making this improvement is not really a priority, and that IE11 has been dropped, I feel like we can close this issue.
