### ISSUE TITLE
"Rerun failed sims" is duplicating

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#83]
![image](https://user-images.githubusercontent.com/679486/74611520-f6529300-50b9-11ea-81e9-df0cb0552824.png)

"Rerun failed sims" is duplicating

**Comment by zepumph** [comment]
Thanks! I'll take a look.

**Comment by zepumph** [comment]
I fixed it and tested locally. Please close if you are happy with it.

**Comment by samreid** [comment]
In one test on my side, it seemed like it reported the wrong one.  But the second test looked great!  Maybe I did something wrong for that first test, or read it wrong.  Closing.
