### ISSUE TITLE
Add the test 'url' field to CT output (and potential other enhancements)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#84]
Please add the test `url` field to CT output.

For example, over in https://github.com/phetsims/gas-properties/issues/177, the output is:

```
gas-properties : phet-io-state-fuzz : require.js : run
Uncaught Error: Assertion failed: invalid dt: 0
Error: Assertion failed: invalid dt: 0
...
```

This doesn't give me enough info to reproduce the problem or test changes.  `phet-io-state-fuzz` is cryptic -- it doesn't tell me what was run,  what query parameters were used, etc.   You have to go search for the test info in continuos-server.js, in this case:

```js
snapshot.testQueue.push( {
  count: 0,
  snapshotName: snapshotName,
  test: [ phetioRepo, 'phet-io-state-fuzz', 'require.js' ],
  url: 'sim-test.html?url=' + encodeURIComponent( `../../${snapshotName}/phet-io-wrappers/state/?sim=${phetioRepo}&phetioDebug&fuzz&postMessageToParent` )
} );
```

If we added the `url` field from the test description, the output would look something like:

```
gas-properties : phet-io-state-fuzz : require.js : run
sim-test.html?url=../../${snapshotName}/phet-io-wrappers/state/?sim=gas-properties&phetioDebug&fuzz&postMessageToParent
Uncaught Error: Assertion failed: invalid dt: 0
Error: Assertion failed: invalid dt: 0
...
```

Assigning to @ariel-phet to prioritize and assign. I'm guessing this will be straightforward.  I'd do it myself, but I have no idea how to test it or install it on the server.

**Comment by pixelzoom** [comment]
@samreid said on Slack:
> I’d love it to be hyperlinked so I can immediately run the same test it failed on

**Comment by pixelzoom** [comment]
That would be nice.  But I'd settle for just knowing what was run, with which query parameters, without having to search continuos-server.js.

**Comment by ariel-phet** [comment]
Might be good to discuss #74 concurrently. However, marking medium priority as work on this (and potentially other CT improvements) would be best to be done after the ES6 migration, so plan to discuss on March 5 2020

**Comment by ariel-phet** [comment]
Adding #85 as possibly worth discussing as well

**Comment by pixelzoom** [comment]
3/5/20 dev meeting:

I'll do this with @jonathanolson's help.

**Comment by pixelzoom** [comment]
I spent ~30 minutes on this and can't make heads or tails of where or how to add URL (or any other field, for that matter).  After consulting with @jonathanolson, he volunteered to handle this - thanks!

**Comment by jonathanolson** [comment]
Noted on Slack that the changes should be applied. Just waiting for the next snapshot to verify.

**Comment by jonathanolson** [comment]
This looks like it's working, closing!

**Comment by pixelzoom** [comment]
Excellent, thanks @jonathanolson. This is already saving me time.
