### ISSUE TITLE
Unit tests won't run on old shas

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#89]
While working on https://github.com/phetsims/phet-io/issues/1648, @samreid @chrisklus and I discovered that our unit tests use a preload from aqua, but aqua isn't in our dependencies.json. This means that checking out old builds potentially won't be able to run unit tests (if master isn't backward compatible to the `-tests.html` file in the checked out repo. 

Is this something to fix? Assigning to @ariel-phet for prioritization.

**Comment by zepumph** [comment]
Tagging @jonathanolson to see if he has any thoughts on this topic.

**Comment by zepumph** [comment]
I think it is probably best for @jonathanolson to comment before priority is mentioned. I don't know of any processes that are trying to run unit tests on old shas. That said it feels backwards and incomplete.

The issue comes down to `aqua` not being in any dependencies.json files, yet `*-tests.html` try to access files from `aqua`. This means that if those files are no longer on master, but are loaded on old shas from test html files, the tests on old shas will break. 

Thus far there have not been any examples of this actually being a problem, which is why I think that @jonathanolson should comment before priority is assigned.

**Comment by jonathanolson** [comment]
I don't think it will necessarily cause any issues, however this seems nice to fix. At least moving forward, we should have this fixed, and ideally I'd like to do a maintenance fix for release branches (it doesn't change things about the published versions, but at least adding in either aqua SHAs OR patching them to work without aqua seems acceptable.

I have a preference for moving the file OUT of aqua, so that we don't store aqua SHAs in sims (both with the maintenance fix on branches, and in master).

To verify that, can we discuss at dev meeting tomorrow?

**Comment by samreid** [comment]
One reason this came up today, is that we wanted to add another aqua-style dependency, please see aqua/js/qunitStart.js.  It seemed reasonable to us that it would live in aqua, but we also considered putting it in another repo that is more simulation-ish. (perhaps chipper or joist? or a new sim-oriented test repo?)

**Comment by zepumph** [comment]
I just linked an issue that came up because CT isn't pulling aqua for CT. My vote is to move qunitStart.js and qunit-connector to chipper, and update test files accordingly.

**Comment by zepumph** [comment]
I ended up moving these files to `chipper/js/sim-tests/`. I wanted to add `qunitStart` to another qunit test file as part of https://github.com/phetsims/axon/issues/276, and this was in part blocking because of how this causes https://github.com/phetsims/tandem/issues/181

Note that I copied history from aqua to chipper for `qunit-connector.js`. Then moved it to `sim-tests/`. It worked very well!

There is still discussion to be had about how we want to maintenance release, and if we like chipper for this long term.

**Comment by jonathanolson** [comment]
The more I think about it, the more I'd like to consider waiting on maintenance unless it's needed (due to the required changes). Thoughts?

Chipper also seems like the best place to me.

**Comment by jonathanolson** [comment]
Also, we'll want to handle pageload-connector.js similarly (chipper home sounds good). It doesn't sound like it fits in the sim-tests directory, should we consider renaming it to fit a wider scope, or place it elsewhere?

**Comment by zepumph** [comment]
How about something like `qunit/`? Or "test-scaffolding"

**Comment by pixelzoom** [comment]
Checking in on status of this issue.  I see a whole bunch of commits from @samreid, not sure how they are related to this issue or if they resolved anything.  So I'll start by assigning to @samreid.

**Comment by samreid** [comment]
I think @zepumph and/or @jonathanolson would be best suited to comment on the status of this issue.

**Comment by zepumph** [comment]
Any sim shas made before April 30 will have broken unit tests when you check them out. I don't think this warrants a maintenance release, and I'm glad that this is now fixed for future releases. I think we are ready to close this issue. @samreid does that sound right to you?

**Comment by samreid** [comment]
In https://github.com/phetsims/aqua/issues/89#issuecomment-622478058 @jonathanolson also recommended moving pageload-connector.js from aqua to chipper.  I'm not sure where that file is used from.  Does that sound right to you?  If so, can you please take the lead on that or let me know if I should?

**Comment by zepumph** [comment]
Good idea. Done above. Again, let's not MR this, seeing that we haven't run into this issue (old shas + broken qunit) in the last 18 months. Closing
