### ISSUE TITLE
Run qunit tests as a pre-commit hook

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#90]
In https://github.com/phetsims/chipper/issues/921 we streamlined the usage of linting as a pre-commit hook, and it has been working extremely well.  I recommend we also add unit tests as a precommit hook.

This was inspired by conversations in https://github.com/phetsims/phet-io/issues/1648 about how we can automatically test phet-io specifications.

**Comment by samreid** [comment]
I committed a first draft for a script that can be used to automatically run unit tests as a precommit hook.  Testing the timing to see if it is fast enough to be used for every commit:

```
axon: 0m1.919s
joist: 0m0.910s
scenery-phet: 0m1.257s
scenery: 0m11.024s
natural-selection (no unit tests): 0m0.133s
```

**Comment by samreid** [comment]
If we move forward with this, here is the commit hook file that we could use.  If linting fails, it doesn't run unit tests:

```
node ../chipper/js/scripts/lint-main.js
if [ $? -ne 0 ]
then
  exit 1
fi

node ../aqua/js/local/qunit-main.js
if [ $? -ne 0 ]
then
  exit 1
fi
```

**Comment by samreid** [comment]
@pixelzoom can you please take a look and recommend whether we should adopt this qunit test phase for phet-info/git-template-dir/hooks/pre-commit ?

**Comment by pixelzoom** [comment]
How long does qunit-main.js take to complete?  If it's significantly longer than lint-main.js, then perhaps it should be done in pre-push instead of pre-commit.

**Comment by samreid** [comment]
I reported timing in https://github.com/phetsims/aqua/issues/90#issuecomment-622453276

**Comment by pixelzoom** [comment]
I wasn't clear on whether the timing  you reported in https://github.com/phetsims/aqua/issues/90#issuecomment-622453276 was for qunit-main.js or the entire pre-commit hook (lint-main.js +_ qunit-main.js).  Assume that the timing is for the pre-commit hook.... I guess I don't mind waiting up to 1 second on each commit.  But you might want to run this past other developers. If there's push back, then moving qunit-main.js to pre-push would likely accomplish the same goal.

**Comment by pixelzoom** [comment]
Doing this in a git hook raises another issue...  Is everyone using git hooks? (I suspect not.) Should they be?

**Comment by samreid** [comment]
The timing I reported is for the qunit tests only.

**Comment by pixelzoom** [comment]
I missed `scenery: 0m11.024s` when I first looked at the timing.  Imo, that's too long to be done in the pre-commit. My vote would be to do it in pre-push.

**Comment by samreid** [comment]
Have you experimented with pre-push hooks using the Webstorm push interface?  Does it respect the hooks and behave accordingly?

**Comment by pixelzoom** [comment]
I have not experimented with WebStorm + pre-push hook.  I didn't find anything relevant in a Google search for "IntelliJ pre-push hook".

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/aqua/issues/90#issuecomment-622508598, I said:
> Doing this in a git hook raises another issue... Is everyone using git hooks? (I suspect not.) Should they be? (I think so.)

When I attempted to publish a dev version early this evening, I discovered:

(1) scenery lint is failing: SimpleDragHandler.js 22:8 error 'Pointer' is defined but never used

(2) sun unit tests are failing: Assertion failed: Cannot simultaneously specify enabledProperty and enabledPropertyOptions

So that establishes that everyone is using git hooks, and they should be. I think it also establishes that people are not running unit tests manually, so they should be added to git hooks. 

Labeling for dev meeting discussion.

**Comment by pixelzoom** [comment]
5/14/2020 dev meeting:

* Add to pre-commit without scenery
* Combine scripts into a single .js (chipper? perennial?) so we can improve without having to reinstall hooks.
* Update documentation that's being added in #171.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/perennial/issues/171#issuecomment-628835038:
> @pixelzoom will add something to PhET Development Overview about how to install hooks.

As I started to do this, I realized that the work outlined in https://github.com/phetsims/aqua/issues/90#issuecomment-628844352 is going to likely make what I write immediately obsolete.  So @samreid would you mind add doc to PhET Developer Overview after you've revised the pre-commit hook and process for installing?

**Comment by samreid** [comment]
Won't the process be the same for installing the git hooks in the first place?  I'll be changing the content phet-info/git-template-dir/hooks/pre-commit, but it will still need to be installed in the same way (via `git init`), right?

**Comment by pixelzoom** [comment]
The current process (adapted from pre-commit doc header) has been added as item 13 to https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#utilities-and-instrumentation-for-development-and-testing.  This seemed like the correct section to add it to, but the use of a numbered list isn't working very well for this section (imo).

**Comment by samreid** [comment]
I think @zepumph recommended putting the precommit.js hook in perennial so it could work across SHAs.  Perennial currently handles code like that via a lazy require statement.

```js
  grunt.registerTask( 'lint-everything', 'lint all js files for all repos', wrapTask( async () => {
    // --disable-eslint-cache disables the cache, useful for developing rules
    const cache = !grunt.option( 'disable-eslint-cache' );


    const activeRepos = getDataFile( 'active-repos' );

    // Don't always require this, as we may have an older chipper checked out
    require( '../../../chipper/js/grunt/lint' )( activeRepos, cache, grunt.option( 'say' ) );
  } ) );
```

It looks like this would fail if '../../../chipper/js/grunt/lint' was undefined.

I'm not sure where this script should live, but I'll try it one spot and we can move it if necessary.

**Comment by samreid** [comment]
I messaged slack:

> I changed the pre-commit hooks on slack to run from a single JS file and include qunit tests (except for scenery).  Details are in https://github.com/phetsims/aqua/issues/90
> 
> After you pull, you will need to update your git hooks before you can commit again, because the old git hook has been deleted.  Instructions for updating are here: https://github.com/phetsims/phet-info/blob/master/git-template-dir/hooks/pre-commit

@pixelzoom or @zepumph can you please pull/test/review?

**Comment by samreid** [comment]
On second thought, I've resurrected lint-main.js for now, so that developers who pull without reading that message will still be able to commit.  When enough developers migrate to the new script, then we can delete the lint-main.js

**Comment by pixelzoom** [comment]
I did a very simple test with WebStorm, and this seems to be working.

Issues, all related to documentation:

- [ ] Instructions in https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#utilities-and-instrumentation-for-development-and-testing (item 13) need to be updated.
- [ ] Make phet-info/.../pre-commit refer to PhET Development Overview for instructions, instead of duplicating instructions in 2 places.
- [ ] Full path to perennial/data/active-repos is unnecessary in instructions. for-each.sh automatically looks in perennial/data/.

**Comment by samreid** [comment]
Thanks for the recommendations, I addressed them in the commit.  @pixelzoom can you please re-review?

**Comment by pixelzoom** [comment]
Looks great.

**Comment by samreid** [comment]
The last thing for this issue is to delete lint-main.js once it no longer appears in anyone's .git hooks directories.  Marking for dev meeting as a checkpoint.  High priority since it will be fast.

**Comment by zepumph** [comment]
Having a hardcoded slash after the localTestingURL was causing bugs for me on Windows http-server, and this was not how we used localTestingURL when generating PhET-iO API files. I removed that hard coded slash, and added support for dynamically adding it if it isn't provided from the client's build-local.

I also found it very hard to debug this, so I added some error logging before process.exit( 1 ) calls. I'm not sure if the `lint`  one is needed, but the unit test one was working well in my case!

@samreid please review my changes.

**Comment by samreid** [comment]
Today @zepumph and I found a circular JSON error when running the unit tests but only in puppeteer and only on @zepumph's machine.  It was fine in @zepumph browser and on @samreid machine.  @zepumph will work around this mysterious issue by using `===` instead of `assert.equal`.

**Comment by samreid** [comment]
> @samreid please review my changes.

Looks good, thanks!  Also, I realized we can use the same strategy we proposed for API file generation, to have node serve the files to puppeteer instead of relying on each developer's localhost.

**Comment by jessegreenberg** [comment]
Discussed on 5/21/20 -

Went over the PSA and all say its OK to remove lint-main.js.

**Comment by samreid** [comment]
lint-main.js has been deleted.

**Comment by chrisklus** [comment]
This is super cool! I tried a commit that should break a unit test and the commit failed. Thanks!

**Comment by zepumph** [comment]
unit tests in phet-io-wrappers are designed to take a sim as a query parameter. This doesn't seem suitable for committing to `phet-io-wrappers`, so I also turned off that unit test above.

**Comment by samreid** [comment]
> Having a hardcoded slash after the localTestingURL was causing bugs for me on Windows http-server, and this was not how we used localTestingURL when generating PhET-iO API files. I removed that hard coded slash, and added support for dynamically adding it if it isn't provided from the client's build-local.

Another way to address this would be to have node serve the files to puppeteer instead of relying on the developer localhost.  We implemented this for https://github.com/phetsims/phet-io/issues/1664 and the same should be possible here.  I'll open a side issue for that and close this one.
