### ISSUE TITLE
add custom tests to CT

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#91]
Add the ability to specify custom tests for a repository.  If this ability is already present in CT, then add documentation about how to add custom tests. 

The most immediate need for this is in testing query parameters.  Common-code and sims have features that are only enabled by specifying sim-specific query parameters.   And those features are not currently being exercised by CT.

Examples of public-facing query parameters that should be tested:

* all of the public-facing query parameters in initialize-globals (`screens`,...)
* Natural Selection: `population`, `mutations`
* Gas Properties: `pressureNoise`
* Beer's Law Lab: `showSoluteAmount`, `concentrationMeterUnits`, `beakerUnits`, `cuvetteSnapInterval`
* pH Scale: `autoFill`
* ...

Assigning to @ariel-phet for prioritization and assignment.  I'd love to have this sometime in the next couple of months for Natural Selection.

**Comment by ariel-phet** [comment]
@jonathanolson could you give me an estimate of what sort of effort this would take (for instance if this ability already exists seems like documentation would be quick) and then reassign to me.

**Comment by jonathanolson** [comment]
This is possible to add to https://github.com/phetsims/perennial/blob/master/js/listContinuousTests.js at the moment, providing sim query parameters, etc.

For example:
```js
tests.push( {
  test: [ 'gas-properties', 'pressure-noise' ],
  type: 'sim-test',
  url: `gas-properties/gas-properties_en.html`,
  queryParameters: 'brand=phet&ea&fuzz&pressureNoise'
} );
```

I haven't added exhaustive documentation about what is supported yet (would need to rely on examples in that file).

**Comment by ariel-phet** [comment]
@pixelzoom will going off the examples above serve your purposes for now?

**Comment by pixelzoom** [comment]
I could probably make this work for Natural Selection. But 3 things:

(1) I've identified a general problem: public-facing sim features that are hidden behind query parameters are not currently being tested.  Do we want to address that problem, so that PhET has better test coverage?  If the answer is "yes", then...

(2)  I don't think we want every developer editing listContinuousTests.js to add sim-specific tests. That's not scalable, and...

(3) Since this involved editing a .js file, it presumable involves stopping/starting CT.  That is again not scalable.  A better solution would have tests defined in a separate (JSON?) description file, managed using GitHub, and CT load test descriptions when it notices that the file has changed. 

Back to @ariel-phet and labeling for dev meeting discussion.

**Comment by jonathanolson** [comment]
> (3) Since this involves editing a .js file, it presumable involves stopping/starting CT. That is again not scalable. A better solution would have tests defined in a description file (JSON?), managed using GitHub, and have CT load test descriptions when it notices that the file has changed.

Definitely does not involve stopping/starting CT in any way. Just commit, and the next snapshot should have the test changes included.

I also don't agree that JSON would be helpful, it's been very helpful to use JS logic instead of cramming TONS of flags into package.json files.

**Comment by pixelzoom** [comment]
Thanks for the clarification, I'll give it a try.

**Comment by pixelzoom** [comment]
Still interested in a reply to this one:

> (1) I've identified a general problem: public-facing sim features that are hidden behind query parameters are not currently being tested. Do we want to address that problem, so that PhET has better test coverage?

**Comment by pixelzoom** [comment]
In the above commit, I added sim-specific query parameter tests for beers-law-lab, gas-properties, natural-selection, and ph-scale.  Local tests with @jonathanolson showed that these were working, but I'll monitor CT.

**Comment by ariel-phet** [comment]
Sounds like we will want to move to a general practice of adding these public facing query parameters to CT, and ideally coming up with a simple test for `?screens=` if possible. Marking for dev meeting to discuss/PSA

**Comment by pixelzoom** [comment]
A few related things that should be discussed:

* Documentation of all query parameter in *QueryParameter.js files
* Use of the `public` field for public-facing query parameters 
* Protocol for how CT knows which query parameters to test
* Add CT tests for other public-facing sim-specific query parameters
* Add CT tests for public-facing common-code query parameters

**Comment by pixelzoom** [comment]
@pixelzoom will add items to CRC:
* add `public` for public-facing query parameters
* add CT tests for public-facing query parameters

We'll use `public` going forward in *QueryParameters.js.  Up to developers whether to address retroactively in their sims.

@samreid suggested adding test values to schema, that CT could then read and test.  Or add query parameter tests to package.json?  Or qunit tests? 

If adding to listContinuousTests.js gets unwieldy in the future, we can revisit.

**Comment by pixelzoom** [comment]
Done, closing.
