### ISSUE TITLE
CT: what is the best default for Sort order?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#92]
Slack discussion in dev-public channel:

> Chris Malley  8:44 AM
CT's default Sort order is "Alphabetical", but I find myself always changing to "Importance".  Is this true for anyone else?  Should "Importance" be the default? If not, could we add a query parameter (`?sort=importance`) for specifying the sort order on startup? (edited) 
> 
> Jonathan Olson  8:45 AM
I’ve used both, but do switch to Importance a lot. I’m 100% fine with that change, but want input from @KatieWoe

Assigned to @KatieWoe for input.

**Comment by KatieWoe** [comment]
I'm used to Alphabetical from old CT, so it hasn't impacted me, but I can see how importance may be more useful. Either way, letting people choose how it loads with a query parameter would be nice so that people could do what is most useful to them.

**Comment by pixelzoom** [comment]
I've gotten used to the current defaults, and we this issue has just been sitting around for > 2 weeks.  So closing.
