### ISSUE TITLE
add lint support to aqua repo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#93]
aqua (including CT) currently does not support `grunt lint`. 

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
@jonathanolson said this issue should be fairly quick to handle.

**Comment by jonathanolson** [comment]
I just went to aqua and ran `grunt lint` and it worked. Can you clarify how to reproduce an issue, or re-check?

```
~/phet/git/aqua # grunt lint
Running "lint" task

Done.
```

**Comment by jonathanolson** [comment]
Also, line 20 of aqua's Gruntfile is running chipper's Gruntfile, similar to how sims run chipper's Gruntfile (so I believe this should work nicely in the future with refactorings).

**Comment by pixelzoom** [comment]
Mea culpa, I must've been running `grunt lint` somewhere else.  Closing.
